### ISSUE TITLE
MobHunting Bug: Error when new players connect when plugin configured to use MYSQL as a backend

### ISSUE THREAD

**Issue by c0mput3** [Rocologo/MobHunting#1]
As i reported a few days ago, when new players login the following error appears

[15:25:02] [Server thread/WARN]: java.sql.SQLException: No value specified for parameter 1
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2205)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2185)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2115)
[15:25:02] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1936)
[15:25:02] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.DatabaseDataStore.getPlayerSettings(DatabaseDataStore.java:188)
[15:25:02] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.DataStoreManager.getPlayerData(DataStoreManager.java:315)
[15:25:02] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.MobHunting.onPlayerJoin(MobHunting.java:1521)
[15:25:02] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:25:02] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:25:02] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:25:02] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:25:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[15:25:02] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:25:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:25:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[15:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[15:25:02] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:25:02] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MobHunting v2.7.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at au.com.mineauz.MobHunting.MobHunting.onPlayerJoin(MobHunting.java:1522) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	... 14 more
[15:25:02] [Server thread/INFO]: c0mput3[/80.229.253.16:58894] logged in with entity id 872 at ([world]-512.2138405148419, 106.0, -1758.1901798203417)

**Comment by Rocologo** [comment]
Upgrading to newest version 2.7.8 will fix this problem.

**Comment by c0mput3** [comment]
Just updated it plugin to version 2.8.1, and i'm afraid there is still the same issue with your plugin and using mysql backend

**Comment by Rocologo** [comment]
I have worked alot on opening / closing database connections. Please test V2.8.7 and let me know if I need to open the ticket again.

**Comment by Rocologo** [comment]
PS. Please post the full error text again if you see this error again, so I can see the new line numbers.
