### ISSUE TITLE
Plugin enables but not working 1.11

### ISSUE THREAD

**Issue by Devilsphere007** [Rocologo/MobHunting#104]
Hi dont know if im the only one with this problem but cant seem to get it to work on the latest 1.11 spigot server. says this in my console after you kill a mob.

[Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.1.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:391) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1075) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntitySkeletonAbstract.die(EntitySkeletonAbstract.java:120) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntitySkeleton.die(EntitySkeleton.java:46) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:932) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1124) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1559) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-4d99fed]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.Messages.learn(Messages.java:331) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:790) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-f950f8e-4d99fed]
	... 23 more

Thanks, any help with this would be greatly appreciated

**Comment by Rocologo** [comment]
Hi, could you please enable debug mode using "/mh debug" then logoff and logon to your server again and let me the MobHunting messages when you logon?

**Comment by Rocologo** [comment]
Also do you use MySql or Sqlite?

**Comment by Rocologo** [comment]
I need your feedback...

**Comment by Rocologo** [comment]
No feedback from @Devilsphere007. Case closed.
