### ISSUE TITLE
Not giving money 4.2.9

### ISSUE THREAD

**Issue by ItsFricco** [Rocologo/MobHunting#111]
Not giving the money but has killstreaks, achivements and everything like that.
Console:
[20:46:37 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.2.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:391) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.EntityLiving.die(EntityLiving.java:1008) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:911) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1585) [spigot.jar:git-Spigot-de459a2-51263e9]
        at de.robingrether.idisguise.management.channel.InjectedPlayerConnection1101.a(InjectedPlayerConnection1101.java:59) [iDisguise.jar:?]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: uk/antiperson/stackmob/StackMob
        at one.lindegaard.MobHunting.compatibility.StackMobCompat.getStackMobAPI(StackMobCompat.java:41) ~[?:?]
        at one.lindegaard.MobHunting.compatibility.StackMobCompat.isStackedMob(StackMobCompat.java:57) ~[?:?]
        at one.lindegaard.MobHunting.modifier.StackedMobBonus.doesApply(StackedMobBonus.java:40) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1052) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        ... 21 more

Not using any database atm.

Help appreciated

**Comment by Rocologo** [comment]
Which version of StackMob do you use? Upgrade if not the newest.

**Comment by Rocologo** [comment]
Or disable integration to StackMob if you cant upgrade

**Comment by ItsFricco** [comment]
ok, that mey have been the issue, gonna try rn

**Comment by ItsFricco** [comment]
Thanks, it is working now. just needed to set disable-integration-mobstacker: to true and it worked.
thanks for the fast help.

**Comment by Rocologo** [comment]
Well it didnt solve the core problem. Are you on StackMob 1.5.6?

**Comment by ItsFricco** [comment]
Mobstacker 1.9.1 actually
