### ISSUE TITLE
MobHunting can't be reloaded with PlugMan (again)

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#113]
As of version 4.3.0, MobHunting can't be reloaded anymore with PlugMan:
```
10.01 14:18:32 [Server] ERROR Error occurred while enabling MobHunting v4.3.0 (Is it up to date?)
10.01 14:18:32 [Server] INFO java.lang.IncompatibleClassChangeError: Class one.lindegaard.MobHunting.storage.MySQLDataStore does not implement the requested interface one.lindegaard.MobHunting.storage.IDataStore
10.01 14:18:32 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:130) ~[?:?]
10.01 14:18:32 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:238) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:299) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Maxetto** [comment]
Also, another Performance Warning:
```
[14:23:55] [Server thread/WARN]: [LagMonitor] Plugin MobHunting is performing a blocking action to socket://localhost:3306 on the main thread This could be a performance hit. Report it to the plugin author
[14:23:55] [Server thread/WARN]: [LagMonitor] 
java.lang.Exception
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:40) [LagMonitor.jar:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_111]
	at java.net.Socket.connect(Socket.java:589) [?:1.8.0_111]
	at java.net.Socket.connect(Socket.java:538) [?:1.8.0_111]
	at java.net.Socket.<init>(Socket.java:434) [?:1.8.0_111]
	at java.net.Socket.<init>(Socket.java:244) [?:1.8.0_111]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at sun.reflect.GeneratedConstructorAccessor104.newInstance(Unknown Source) [?:1.8.0_111]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_111]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:440) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:138) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:108) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at one.lindegaard.MobHunting.storage.MySQLDataStore.setupConnection(MySQLDataStore.java:51) [MobHunting-4.3.0.jar:?]
	at one.lindegaard.MobHunting.storage.DatabaseDataStore.updatePlayerSettings(DatabaseDataStore.java:940) [MobHunting-4.3.0.jar:?]
	at one.lindegaard.MobHunting.storage.DataStoreManager.updatePlayerSettings(DataStoreManager.java:225) [MobHunting-4.3.0.jar:?]
	at one.lindegaard.MobHunting.PlayerSettingsManager.save(PlayerSettingsManager.java:109) [MobHunting-4.3.0.jar:?]
	at one.lindegaard.MobHunting.PlayerSettingsManager.onPlayerQuit(PlayerSettingsManager.java:80) [MobHunting-4.3.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:312) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Rocologo** [comment]
This is again an error in LagMonitor you have to report the error to games647. 

"/plugman reload mobhunting" works fine when LagMonitor is not loaded.

**Comment by Maxetto** [comment]
Happened because an interface changed during the reload (Because different versions).

Let's say it's solved.

**Comment by Sikatsu** [comment]
@Rocologo 

http://pastebin.com/krMDjTtP
