### ISSUE TITLE
Non-sentinel NPCs treated badly

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#114]
Environment: Spigot 1.11.2, MH 4.3.2, plus WE/WG, PEX, MV, Citizens+Sentinel, and a myriad of other plugins, all latest pulls.

Installed MH for first time. On startup, log errors are generated for six non-sentinel NPCs. There is no apparent issue with the NPCs. This is typical of the errors:

> [17:08:57] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobHunting v4.3.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:281) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.World.addEntity(World.java:1038) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.WorldServer.addEntity(WorldServer.java:1064) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:223) [citizens-2.0.21-b1465.jar:?]
        at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:42) [citizens-2.0.21-b1465.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:199) [citizens-2.0.21-b1465.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:139) [citizens-2.0.21-b1465.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens-2.0.21-b1465.jar:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:305) [citizens-2.0.21-b1465.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.ConfigManager.getKillConsoleCmd(ConfigManager.java:1893) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.reinforcementMobSpawn(MobHuntingManager.java:1396) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        ... 19 more

**Comment by Rocologo** [comment]
I hope I found the bug. Please help me test build 244 or newer and let me if you still have the error.

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by SlimeDog** [comment]
Rudimentary test: Install b244, kill a mob.
- No log errors :)
- Reward updated

Thanks for the fast turnaround.

**Comment by Rocologo** [comment]
Yes, it was an easy test, but I didnt see the error on my server, so I needed your help. :-)
