### ISSUE TITLE
ERROR: Could not pass event CreatureSpawnEvent to MobHunting v4.4.0 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by TomPiXX** [Rocologo/MobHunting#128]
We're running Thermos 1.7.10 (a Cauldron fork) and get errors:

`[09:42:33] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobHunting v4.4.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:272) [CraftEventFactory.class:1.7.10-1614.58]
	at net.minecraft.world.World.addEntity(World.java:1817) [ahb.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1768) [ahb.class:?]
	at drzhark.customspawner.CustomSpawner.performWorldGenSpawning(CustomSpawner.java:793) [CustomSpawner.class:?]
	at drzhark.customspawner.EventHooks.peformCustomWorldGenSpawning(EventHooks.java:51) [EventHooks.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_209_EventHooks_peformCustomWorldGenSpawning_Populate.invoke(.dynamic) [?:1.7.10-1614.58]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.58]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
	at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:36) [TerrainGen.class:1.7.10-1614.58]
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:434) [aqz.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442) [ms.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.chunkLoadPostProcess(CraftWorld.java:290) [CraftWorld.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.loadChunk(CraftWorld.java:273) [CraftWorld.class:1.7.10-1614.58]
	at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:210) [WorldBorder%201.8.6.jar:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getName()Ljava/lang/String;
	at one.lindegaard.MobHunting.ConfigManager.getBaseKillPrize(ConfigManager.java:1989) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.spawnerMobSpawn(MobHuntingManager.java:1456) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	... 24 more`

**Comment by Rocologo** [comment]
I dont have a Thermos test server, so I will need your help. 

It is basically the Minecraft 1.7.10 version which is hard to support, but I give it a try... I have fix the error in the ConfigurationManager.class but you might find more similar bugs.

Please test Build 271 or never
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by TomPiXX** [comment]
Thanks, mate, I will give it a try.
You may want to take a look at the latest thermos build, but I will help you as much as I can.

https://yivesmirror.com/grab/thermos/Thermos-1.7.10-1614-58.zip

**Comment by Rocologo** [comment]
I doesn't work.

![image](https://cloud.githubusercontent.com/assets/1008133/22643778/4366aecc-ec60-11e6-9476-b68e5b53800f.png)

No matter what I click at dont get any file????

**Comment by Rocologo** [comment]
Just to repeat

> Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getName()Ljava/lang/String; at one.lindegaard.MobHunting.ConfigManager.getBaseKillPrize(ConfigManager.java:1989)

This one is in MobHunting one.lindegaard.MobHunting.ConfigManager at line 1989 and this is fixed now :-)

**Comment by TomPiXX** [comment]
You may want to try this link:
http://yivesmirror.com/files/thermos/Thermos-1.7.10-1614-58.zip

https://yivesmirror.com/downloads/thermos

**Comment by Rocologo** [comment]
It worked.

I can now create a Thermos test server, but I will not spend hours finding bugs on this version. I have only a few Minecraft 1.7.10 users. But I will try to fix any bug you find, and for this I need the Thermos test-server.

I close this ticket now. Create a new ticket if you find new bugs.

**Comment by Rocologo** [comment]
Im trying to get the Thermos server up and running but Citizens2 fails. Which version do you use?

**Comment by TomPiXX** [comment]
Version of Citizens? We're using Factions.

**Comment by Rocologo** [comment]
Okay, you dont use Citizens.

Citizens is needed if you want to create MasterMobHunters. 

https://www.spigotmc.org/attachments/mastermobhunters-small-png.107433/
