### ISSUE TITLE
ERROR: Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by TomPiXX** [Rocologo/MobHunting#129]
`[12:54:37] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to MobHunting v4.4.1-SNAPSHOT-B271
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:365) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: SLIME_BLOCK
	at com.github.tnerevival.core.material.MaterialHelper.<clinit>(MaterialHelper.java:179) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:103) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:171) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.work(Transaction.java:240) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:53) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:159) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:153) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:90) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:80) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.depositPlayer(TNEVaultEconomy.java:90) ~[?:?]
	at one.lindegaard.MobHunting.rewards.RewardManager.depositPlayer(RewardManager.java:68) ~[?:?]
	at one.lindegaard.MobHunting.rewards.RewardListeners.onPlayerMoveOverMoneyEvent(RewardListeners.java:133) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	... 13 more
`

**Comment by Rocologo** [comment]
This is not a MobHunting error: 

> Caused by: java.lang.NoSuchFieldError: SLIME_BLOCK at com.github.tnerevival.core.material.MaterialHelper.<clinit>(MaterialHelper.java:179) ~[?:?] at 

The error is in this Method: com.github.tnerevival.core.material.MaterialHelper at line 179. And this is not mobhunting.
