### ISSUE TITLE
ERROR: Could not pass event PlayerPickupItemEvent

### ISSUE THREAD

**Issue by TomPiXX** [Rocologo/MobHunting#130]
`[12:54:37] [Server thread/ERROR]: Could not pass event PlayerPickupItemEvent to MobHunting v4.4.1-SNAPSHOT-B271
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:413) [xk.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:692) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:683) [yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1954) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:399) [mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:488) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.tnerevival.core.material.MaterialHelper
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:103) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:171) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.work(Transaction.java:240) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:53) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:159) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:153) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:90) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:80) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.depositPlayer(TNEVaultEconomy.java:90) ~[?:?]
	at one.lindegaard.MobHunting.rewards.RewardManager.depositPlayer(RewardManager.java:68) ~[?:?]
	at one.lindegaard.MobHunting.rewards.RewardListeners.onPickupMoney(RewardListeners.java:44) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	... 19 more
`

**Comment by Rocologo** [comment]
Again, this is not a MobHunting error:

>  Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.tnerevival.core.material.MaterialHelper at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:103) ~[?:?] at

The error is in com.github.tnerevival.utils.AccountUtils at line 103. and this is not MobHunting.
