### ISSUE TITLE
Error using Spigot 1.11 and Java 8 ! :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#149]
22:22:00] [Server thread/WARN]: one.lindegaard.MobHunting.storage.DataStoreException: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[22:22:00] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.updatePlayerSettings(DatabaseDataStore.java:991)
[22:22:00] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DataStoreManager.updatePlayerSettings(DataStoreManager.java:225)
[22:22:00] [Server thread/WARN]: 	at one.lindegaard.MobHunting.PlayerSettingsManager.save(PlayerSettingsManager.java:109)
[22:22:00] [Server thread/WARN]: 	at one.lindegaard.MobHunting.PlayerSettingsManager.onPlayerQuit(PlayerSettingsManager.java:80)
[22:22:00] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor1236.invoke(Unknown Source)
[22:22:00] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:22:00] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:379)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1054)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.disconnect(PlayerConnection.java:245)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:218)
[22:22:00] [Server thread/WARN]: 	at fr.xephi.authme.task.TimeoutTask.run(TimeoutTask.java:31)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:22:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[22:22:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[22:22:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:22:00] [Server thread/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[22:22:00] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:909)
[22:22:00] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:921)
[22:22:00] [Server thread/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:886)
[22:22:00] [Server thread/WARN]: 	at org.sqlite.core.DB.exec(DB.java:155)
[22:22:00] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:165)
[22:22:00] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.updatePlayerSettings(DatabaseDataStore.java:986)
[22:22:00] [Server thread/WARN]: 	... 22 more

**Comment by Rocologo** [comment]
This is not releated to Spigot + Java 8 - I juse the same versions on both my test servers and on mc.lindegarrd.one.

Which version of the plugin do you use?

**Comment by TheIntelloBox** [comment]
The latest. ;)

**Comment by Rocologo** [comment]
It does not look like the newest, the line numbers does match the newest version??? Please check that you dont have two jar files in the plugins folder.

**Comment by Rocologo** [comment]
Or try /mh version

**Comment by TheIntelloBox** [comment]
I haven't got 2 JARS and I'm on 4.4.7.

**Comment by krustymk** [comment]
this looks the same as the issue i reported yesterday http://pastebin.com/Ta5iV00H or very similar #154

**Comment by TheIntelloBox** [comment]
Yeah.

**Comment by TheIntelloBox** [comment]
MobHunting v4.4.7 Total: 7.36 s Pct: 0.15%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       0.12%	6,010.65%	  6.01 s	 3,005.32 ms	 0.0	       0.0k	    Task: BountyManager$1(interval 72000)

**Comment by Rocologo** [comment]
Please let me know if you see the sqlite locking problem when you are on v4.4.8

**Comment by TheIntelloBox** [comment]
Fantastic ! :D

**Comment by Rocologo** [comment]
Does this mean that you think it works now?

**Comment by TheIntelloBox** [comment]
Yes. :D
