### ISSUE TITLE
NPE on disable (shutdown)

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#158]
Spigot 1.11.2, MH 4.4.8

> [12:27:23][Server thread/INFO]: [MobHunting] Disabling MobHunting v4.4.8
[12:27:23] [Server thread/ERROR]: Error occurred while disabling MobHunting v4.4.8 (Is it up to date?)
java.lang.NullPointerException
        at one.lindegaard.MobHunting.MobHunting.onDisable(MobHunting.java:304) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

That is the complete error message. Next log line refers to a different plugin. There are no later references to MobHunting.

**Comment by Rocologo** [comment]
I have found the bug, it only happens when the fishing reward is disabled. This will be fixed in next release.

**Comment by SlimeDog** [comment]
Thanks. Confirm that fishing rewards are disabled on my server. :)

**Comment by Rocologo** [comment]
Fixed in v4.4.9
