### ISSUE TITLE
NPE on disable

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#163]
Spigot 1.11.2 latest, MH 4.4.8

> [01:27:42] [Server thread/INFO]: [MobHunting] Disabling MobHunting v4.4.8
[01:27:42] [Server thread/ERROR]: Error occurred while disabling MobHunting v4.4.8 (Is it up to date?)
java.lang.NullPointerException
        at one.lindegaard.MobHunting.MobHunting.onDisable(MobHunting.java:304) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.11.2.jar-2017-02-16-2124:git-Spigot-d4f98a3-4448a7e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Rocologo** [comment]
Fixed in V4.4.9

**Comment by SlimeDog** [comment]
Oh right. #158. Sorry.
