### ISSUE TITLE
Start-up issues

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#175]
MobHunting 4.5.5
I moved the existing configuration and started the server, in order to generate the MobHunting files and database from scratch.

grep MobHunting logs/latest.log
> [18:20:45] [Server thread/INFO]: [MobHunting] Loading MobHunting v4.5.5
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling MobHunting v4.5.5
[18:21:14] [Server thread/INFO]: [MobHunting] Language file en_US.lang does not exist in JAR.
[18:21:14] [Server thread/ERROR]: [MobHunting] Language file does not exist. Creating a new file based on en_US. You need to translate the file yourself.
[18:21:14] [Server thread/INFO]: [MobHunting] Updated en_US.lang.lang language file with missing keys
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Minecraft.kill) in language fileen_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Minecraft.assist) in language file en_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MythicMobs.kill) in language fileen_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MythicMobs.assist) in language file en_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Citizens.kill) in language fileen_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Citizens.assist) in language file en_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.TARDISWeepingAngels.kill) in language fileen_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.TARDISWeepingAngels.assist) in language file en_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.CustomMobs.kill) in language fileen_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.CustomMobs.assist) in language file en_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MysteriousHalloween.kill) in language fileen_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MysteriousHalloween.assist) in language file en_US.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Updated en_US.lang.lang language file
[18:21:14] [Server thread/INFO]: [MobHunting] Sorted en_US.lang.lang translation
[18:21:14] [Server thread/WARN]: java.io.FileNotFoundException: plugins/MobHunting/lang/en_US.lang (No such file or directory)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.detectEncoding(Messages.java:264)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.loadLang(Messages.java:291)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.exportDefaultLanguages(Messages.java:72)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:109)
[18:21:14] [Server thread/INFO]: [MobHunting] Language file zh_CN.lang does not exist in JAR.
[18:21:14] [Server thread/ERROR]: [MobHunting] Language file does not exist. Creating a new file based on en_US. You need to translate the file yourself.
[18:21:14] [Server thread/INFO]: [MobHunting] Updated zh_CN.lang.lang language file with missing keys
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Minecraft.kill) in language filezh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Minecraft.assist) in language file zh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MythicMobs.kill) in language filezh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MythicMobs.assist) in language file zh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Citizens.kill) in language filezh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Citizens.assist) in language file zh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.TARDISWeepingAngels.kill) in language filezh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.TARDISWeepingAngels.assist) in language file zh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.CustomMobs.kill) in language filezh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.CustomMobs.assist) in language file zh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MysteriousHalloween.kill) in language filezh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MysteriousHalloween.assist) in language file zh_CN.lang.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Updated zh_CN.lang.lang language file
[18:21:14] [Server thread/INFO]: [MobHunting] Sorted zh_CN.lang.lang translation
[18:21:14] [Server thread/WARN]: java.io.FileNotFoundException: plugins/MobHunting/lang/zh_CN.lang (No such file or directory)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.detectEncoding(Messages.java:264)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.loadLang(Messages.java:291)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.exportDefaultLanguages(Messages.java:72)
[18:21:14] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:109)
[18:21:14] [Server thread/ERROR]: [MobHunting] Language file does not exist. Creating a new file based on en_US. You need to translate the file yourself.
[18:21:14] [Server thread/INFO]: [MobHunting] Updated en_US.lang language file with missing keys
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Minecraft.kill) in language fileen_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Minecraft.assist) in language file en_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MythicMobs.kill) in language fileen_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MythicMobs.assist) in language file en_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Citizens.kill) in language fileen_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.Citizens.assist) in language file en_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.TARDISWeepingAngels.kill) in language fileen_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.TARDISWeepingAngels.assist) in language file en_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.CustomMobs.kill) in language fileen_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.CustomMobs.assist) in language file en_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MysteriousHalloween.kill) in language fileen_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Creating missing key (stats.MysteriousHalloween.assist) in language file en_US.lang
[18:21:14] [Server thread/INFO]: [MobHunting] Updated en_US.lang language file
[18:21:14] [Server thread/INFO]: [MobHunting] Sorted en_US.lang translation
[18:21:14] [Server thread/INFO]: [MobHunting] Database version 3 detected.
[18:21:14] [Server thread/INFO]: [MobHunting] 61 Minecraft Vanilla Mobs was inserted to mh_Mobs
[18:21:14] [Server thread/INFO]: [MobHunting] Rename mh_Players to mh_PlayersV2.
[18:21:14] [Server thread/INFO]: [MobHunting] Adding RandomBounty Player to MobHunting Database.
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling compatibility with Essentials (2.0.1-b468)
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling compatibility with WorldEdit (6.1.7-SNAPSHOT;3680-a4455e8)
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling compatibility with WorldGuard (6.2.1-SNAPSHOT;1703-85693b9)
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling compatibility with ProtocolLib (4.2.1-SNAPSHOT-b347).
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling compatibility with MinigamesLib (v1.14.14-20170105.211143)
[18:21:14] [Server thread/INFO]: [MobHunting] Enabling compatibility with Citizens (2.0.21-SNAPSHOT (build 1472))
[18:21:17] [Server thread/INFO]: [MobHunting] Checking for new updates...
[18:21:22] [Server thread/INFO]: [MobHunting] No update found.
[18:21:29] [Server thread/WARN]: java.io.FileNotFoundException: plugins/MobHunting/lang/zh_CN.lang (No such file or directory)
[18:21:29] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.detectEncoding(Messages.java:264)

The en_US.lang language file was created. Also en_US.lang.lang and zh_CN.lang.lang. All contain the same English strings. In a previous version (not sure how far back), the Chinese file contained Chinese character representation. In addition, I'm not sure why there are log errors for a straightforward initialization.

> [18:21:29] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.loadLang(Messages.java:291)
[18:21:29] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.injectMissingMobNamesToLangFile(Messages.java:137)
[18:21:29] [Server thread/WARN]: 	at one.lindegaard.MobHunting.Messages.injectMissingMobNamesToLangFiles(Messages.java:131)
[18:21:29] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting$1.run(MobHunting.java:255)
[18:21:29] [Craft Scheduler Thread - 0/INFO]: [MobHunting] 15 Citizens NPC's was inserted to mh_Mobs

No Citizens were injected into the language files. Only 15 of the 25 existing Citizens were injected into the _mh_Mobs_ sqlite table.

**Comment by Rocologo** [comment]
Strange.... i tested this many times yesterday. I looks like you have added .lang in your config.yml?

**Comment by Rocologo** [comment]
Is the Sentinel Trait added to all 25 or only 15?

**Comment by Rocologo** [comment]
Sorry i did not read your post properly. I didnt try to remove the hole config.yml, i only changed the setting to existing/non-existing language name i will have to do the same test.

**Comment by SlimeDog** [comment]
15 Sentinels

**Comment by Rocologo** [comment]
It only add the sentinel/sentry you can kill. I changed that a while ago.

**Comment by SlimeDog** [comment]
Excellent. Thanks. Actually, these cannot be killed, since they are invincible, but I understand the distinction.

**Comment by Rocologo** [comment]
I found the bug, and will make another fast release, because I don't like this error.

**Comment by Rocologo** [comment]
Fixed in v4.5.6
