### ISSUE TITLE
Some issue with SQL in latest update!

### ISSUE THREAD

**Issue by mrho225** [Rocologo/MobHunting#179]
I got this error sometime in console with latest update.
`[09:46:59 WARN]: one.lindegaard.MobHunting.storage.DataStoreException: java.sql.SQLException: Column count doesn't match value count at row 1
[09:46:59 WARN]:        at one.lindegaard.MobHunting.storage.MySQLDataStore.savePlayerStats(MySQLDataStore.java:284)
[09:46:59 WARN]:        at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:47)
[09:46:59 WARN]:        at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:13)
[09:46:59 WARN]:        at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:445)
[09:46:59 WARN]: Caused by: java.sql.SQLException: Column count doesn't match value count at row 1
[09:46:59 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[09:46:59 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[09:46:59 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[09:46:59 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[09:46:59 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[09:46:59 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[09:46:59 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[09:46:59 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[09:46:59 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[09:46:59 WARN]:        at one.lindegaard.MobHunting.storage.MySQLDataStore.savePlayerStats(MySQLDataStore.java:271)
[09:46:59 WARN]:        ... 3 more
`

**Comment by Rocologo** [comment]
Please test this test this SNAPSHOT 

https://dl.dropboxusercontent.com/u/36067670/MobHunting/MobHunting-4.6.1-SNAPSHOT-B306.jar
