### ISSUE TITLE
Some console error

### ISSUE THREAD

**Issue by mrho225** [Rocologo/MobHunting#185]
I just saw this error in my console. Hope you have time to check it. Thanks

`[21:49:06 ERROR]: Could not pass event PlayerDeathEvent to MobHunting v4.6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:410) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityPlayer.die(EntityPlayer.java:417) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:502) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityArrow.a(EntityArrow.java:286) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityArrow.A_(EntityArrow.java:194) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityTippedArrow.A_(EntityTippedArrow.java:86) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.MobHuntingManager.onPlayerDeath(MobHuntingManager.java:464) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        ... 20 more
`

**Comment by Rocologo** [comment]
Fixed in V4.6.2
