### ISSUE TITLE
Integration issues with towny

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#193]
Spigot 1.11.2
MH 4.6.5

Towny not installed, configuration:

```
towny:

  # Disable integration with Towny.
  # http://towny.palmergames.com/
  disable-integration-towny: true
```

On (almost) every kill:

```
[21:28:13 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.6.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.EntityArrow.a(EntityArrow.java:286) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.EntityArrow.A_(EntityArrow.java:194) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.EntityTippedArrow.A_(EntityTippedArrow.java:86) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:819) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:819) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar-2017-03-20-0748:git-Spigot-96235ab-257d6cd]
        ... 19 more
```

When a new integration is added, please default to disabled = true. And please test with the integrated plugin not installed.

**Comment by Rocologo** [comment]
Fixed in v4.6.6., I forgot to test without Towny.
