### ISSUE TITLE
There are some my sql errror tho :)

### ISSUE THREAD

**Issue by mrho225** [Rocologo/MobHunting#197]
`[18:24:21] [Server thread/WARN]: one.lindegaard.MobHunting.storage.DataStoreException: java.sql.BatchUpdateException: Cannot add or update a child row: a foreign key constraint fails (`mc_MobHunting`.`mh_Bounties`, CONSTRAINT `mh_Bounties_Player_Id_1` FOREIGN KEY (`BOUNTYOWNER_ID`) REFERENCES `mh_Players` (`PLAYER_ID`) ON DELETE CASCADE)
[18:24:21] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.insertBounty(DatabaseDataStore.java:889)
[18:24:21] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DataStoreManager.insertBounty(DataStoreManager.java:138)
[18:24:21] [Server thread/WARN]: 	at one.lindegaard.MobHunting.bounty.BountyManager.addBounty(BountyManager.java:88)
[18:24:21] [Server thread/WARN]: 	at one.lindegaard.MobHunting.bounty.BountyManager.createRandomBounty(BountyManager.java:530)
[18:24:21] [Server thread/WARN]: 	at one.lindegaard.MobHunting.bounty.BountyManager$1.run(BountyManager.java:55)
[18:24:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[18:24:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[18:24:21] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[18:24:21] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[18:24:21] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[18:24:21] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[18:24:21] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:24:21] [Server thread/WARN]: Caused by: java.sql.BatchUpdateException: Cannot add or update a child row: a foreign key constraint fails (`mc_MobHunting`.`mh_Bounties`, CONSTRAINT `mh_Bounties_Player_Id_1` FOREIGN KEY (`BOUNTYOWNER_ID`) REFERENCES `mh_Players` (`PLAYER_ID`) ON DELETE CASCADE)
[18:24:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:24:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:24:21] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:24:21] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
[18:24:21] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.insertBounty(DatabaseDataStore.java:882)
[18:24:21] [Server thread/WARN]: 	... 11 more
[18:24:21] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`mc_MobHunting`.`mh_Bounties`, CONSTRAINT `mh_Bounties_Player_Id_1` FOREIGN KEY (`BOUNTYOWNER_ID`) REFERENCES `mh_Players` (`PLAYER_ID`) ON DELETE CASCADE)
[18:24:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:24:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:24:21] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:24:21] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[18:24:21] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
[18:24:21] [Server thread/WARN]: 	... 14 more`

**Comment by Rocologo** [comment]
What version are you on?

**Comment by mrho225** [comment]
This is my mysql version Roco
mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by Rocologo** [comment]
I meant the MobHunting version? ☺

**Comment by mrho225** [comment]
Latest one tho V4.6.8

**Comment by Rocologo** [comment]
Could you please install newest snapshot build 324 or newer from my Jenkins server, and enable debug information with "/mh debug" and then show me the debug information before this error happens?

http://jenkins.lindegaard.one:8180/job/MobHunting/

I use MySQL on my own production server mc.lindegaard.one and I dont see this error there, so I have to find the reason why it fails on your server. I have added some more debug information in build 324.

**Comment by Rocologo** [comment]
If I dont hear from you within a few days I assume that this is fixed and I close this ticket.
