### ISSUE TITLE
Force metric to be enable ;(

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#2]
https://github.com/Rocologo/MobHunting/blob/master/src/au/com/mineauz/MobHunting/MobHunting.java#L1752 delete de metrics.enable()

**Comment by Rocologo** [comment]
Not for now. I do a lot of hard work on this plugin and it is important for me that I know how many uses my plugin. I have updated the metric file to R8-SNAPSHOT.

**Comment by FlashLight34** [comment]
oh i see, you force all players to send information with no choice :( ok now i create a plugin to deactivate this one :D

**Comment by FlashLight34** [comment]
that it`[17:13:22 INFO]: [MobHunting] Enabling MobHunting v2.7.9
[17:13:22 INFO]: [MobHunting] Enabling compatability with Essentials (2.0.1-b341)
[17:13:22 INFO]: [MobHunting] Enabling compatability with WorldEdit (6.1.1-SNAPSHOT;3463-219d2da)
[17:13:22 INFO]: [MobHunting] Enabling compatability with WorldGuard (6.1.2-SNAPSHOT;1653-65e48d1)
[17:13:22 INFO]: [MobHunting] Compatability with Citizens2 is disabled in config.yml
[17:13:22 INFO]: MobHunting reloaded successfully.
[17:13:22 INFO]: maetika issued server command: /i 82 64
[17:13:22 WARN]: tintin1312 moved too quickly! -3.6697947486327394,-4.0,8.496989627925814
[17:13:23 INFO]: [MobHunting] Checking for new updates...
[17:13:23 WARN]: Exception in thread "Craft Scheduler Thread - 874" 
[17:13:23 WARN]: org.apache.commons.lang.UnhandledException: Plugin MobHunting v2.7.9 generated an exception while executing task 313174
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at org.mcstats.Metrics.postPlugin(Metrics.java:335)
at org.mcstats.Metrics.access$400(Metrics.java:57)
at org.mcstats.Metrics$1.run(Metrics.java:223)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

[17:13:23 INFO]: [MobHunting] No update found.
[17:13:23 INFO]: [Setrankmod] Turn metric to off!!`

**Comment by FlashLight34** [comment]
for the metric error, i changed signedit plugin for another one and now no more error

**Comment by Rocologo** [comment]
Ahh. I knew it was an old plugin. :-) 

I use editsigns because it is better updated. Signedit has not been updated for long.
