### ISSUE TITLE
Mobhunting server crash (possibly to do with protocollib?)

### ISSUE THREAD

**Issue by SucceededKiller** [Rocologo/MobHunting#205]
Hey,

ProtocolLib 4.2.0 and Mobhunting 4.7.2

Server has been crashing a few times, log has this:

https://paste.ee/p/d2lA5
https://paste.ee/p/5R1ue

The logs immediately prior don't seem very interesting with debug on, but here it is:

```
[21:12:26] [Thread-108/INFO]: [MobHunting][Debug] achievements is disabled with permission 'mobhunting.achievements.disabled' for player _Aether_Ace_
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] ===================== Farm detection =======================
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] ======================== New kill ==========================
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] petethepug killed a Skeleton (Minecraft)
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] Permission 'mobhunting.mobs.*' or 'mobhunting.mobs.SKELETON' not set, defaulting to True.
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] Basic Prize=F6 for killing a Skeleton
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] Found a blacklisted grinding area = Location{world=CraftWorld{name=helloclan},x=-80.16179019944846,y=6.0,z=-2372.700155887823,pitch=0.0,yaw=242.07666}, range=50.0
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] Found a blacklisted grinding area = Location{world=CraftWorld{name=helloclan},x=-80.16179019944846,y=6.0,z=-2372.700155887823,pitch=0.0,yaw=242.07666}, range=50.0
[21:12:27] [Thread-108/INFO]: [MobHunting][Debug] ======================= kill ended =========================

``````

Also getting errors like this occasionally, not sure if it's anything to worry about?
```
[21:11:52] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.7.2
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.11.2.jar:git-Paper-1078]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1100) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityZombie.die(EntityZombie.java:429) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:954) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityZombie.damageEntity(EntityZombie.java:163) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityPigZombie.damageEntity(SourceFile:148) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.e(EntityLiving.java:1195) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.Block.fallOn(Block.java:527) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.Entity.a(Entity.java:1046) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.a(EntityLiving.java:188) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:842) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1787) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2081) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:502) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityZombie.n(EntityZombie.java:155) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1916) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:245) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1740) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1715) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1532) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:621) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:898) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1078]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.PlayerSettingsManager.getPlayerSettings(PlayerSettingsManager.java:37) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:751) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.11.2.jar:git-Paper-1078]
	... 33 more
```

You'll have to let me know if there's anything else you need.

Thanks in advance. :)

**Comment by Rocologo** [comment]
You are close but it has nothing to do with ProtocolLib, except that the bug is in the new Farm detection where I forgot that the killer can be "null" which causes this error. This is fixed in V4.7.3.

Thank you for making a ticket,
