### ISSUE TITLE
Please look at the reasons for the error and now I update to V4.7.2

### ISSUE THREAD

**Issue by BenLiHao** [Rocologo/MobHunting#206]
`[13:02:25 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.6.8
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1078) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:932) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityEnderman.damageEntity(EntityEnderman.java:276) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.attack(EntityMyPet.java:342) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:115) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1007) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.n(EntityMyPet.java:939) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1892) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.A_(EntityMyPet.java:1160) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1653) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.World.g(World.java:1628) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1454) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.modifier.CriticalModifier.canCriticalHit(CriticalModifier.java:34) ~[?:?]
        at one.lindegaard.MobHunting.modifier.CriticalModifier.doesApply(CriticalModifier.java:48) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1267) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor310.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        ... 25 more`

**Comment by Rocologo** [comment]
Please update the plugin to V4.7.3

**Comment by Rocologo** [comment]
fixed in v4.7.4

**Comment by BenLiHao** [comment]
Thank you, I like your efficiency. Support you.
