### ISSUE TITLE
bounty problems on 1.11

### ISSUE THREAD

**Issue by spamattack** [Rocologo/MobHunting#212]
Player heads all end up as Alex too??
I am unable to set or claim/remove previous bounty. This came on after one of the last updates. Internal error while attempting.... 
[00:19:32] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mh' in plugin MobHunting v4.7.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.commands.BountyCommand.onCommand(BountyCommand.java:145) ~[?:?]
	at one.lindegaard.MobHunting.commands.CommandDispatcher.onCommand(CommandDispatcher.java:116) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]

**Comment by Rocologo** [comment]
Okay, I had to rewrite a lot of code ...  Please help me test build 343 or newer. Its very hard to test Bounties on my test-server because you have to be two player online ...
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by spamattack** [comment]
Ok that fixes the bounty errors but when you kill the player or use the head command it still gives you Alex?? Any ideas?

**Comment by Rocologo** [comment]
This sometimes happens if the your internet connection is poor or if the Majong servers dont send the skin fast enough. The head usually get get the correct skin after some time, without doing anything?

**Comment by Rocologo** [comment]
Are you still having problems with mobheads / alex heads?

**Comment by spamattack** [comment]
Yes, any of the players heads turn out to be Alex. You can try server is playvanilla.us

**Comment by Rocologo** [comment]
1) Please enable debug using "/mh debug"
2) And then try "/mobhunt head drop Rocologo"
3) and show me the debug information in the server log

**Comment by spamattack** [comment]
Hi,I tried it with your player name and console said user unknown so I tried with mine and get the same error?? ---Windows detected mouse movement-->You must restart to save changes Y/N--- 

    On Sunday, May 7, 2017 2:23 PM, Rocologo <notifications@github.com> wrote:
 

    
   - Please enable debug using "/mh debug"
   - And then try "/mobhunt head drop Rocologo"
   - and show me the debug information in the server log

**Comment by Rocologo** [comment]
Ahh, yes you can or cause not use my playername since I have never been on your server ☺its fine using your own playername, but could you please show me the output in the server log?

**Comment by spamattack** [comment]
[19:39:44] [Server thread/INFO]: spamattack issued server command: /mh debug[19:39:55] [Server thread/INFO]: spamattack issued server command: /mh[19:40:11] [Server thread/INFO]: spamattack issued server command: /mh head[19:40:19] [Server thread/INFO]: spamattack issued server command: /mh head drop spamattack[19:40:32] [Server thread/INFO]: spamattack issued server command: /mh debug[19:40:35] [Server thread/INFO]: spamattack issued server command: /mh head drop spamattack
Error says spamattack is unknown no other info in debug mode ---Windows detected mouse movement-->You must restart to save changes Y/N--- 

    On Monday, May 8, 2017 1:52 PM, Rocologo <notifications@github.com> wrote:
 

 Ahh, yes you can or cause not use my playername since I have never been on your server ☺its fine using your own playername, but could you please show me the output in the server log?—

**Comment by Rocologo** [comment]
Ahh, it looks like you have a name conflict. Try again using mobhunt instead of mh. Enable debug, run the command and show me the log.

I did not realize  "---Windows detected mouse movement-->You must restart to save changes Y/N---" was from your log, i have never seen this error before.

**Comment by spamattack** [comment]
I get the exact same results as before using /mh ---Windows detected mouse movement-->You must restart to save changes Y/N--- 

    On Monday, May 8, 2017 9:46 PM, Rocologo <notifications@github.com> wrote:
 

 Ahh, it looks like you have a name conflict. Try again using mobhunt instead of mh. Enable debug, run the command and show me the log.I did not realize "---Windows detected mouse movement-->You must restart to save changes Y/N---" was from your log, i have never seen this error before.—

**Comment by spamattack** [comment]
lLolOL this is my sig line ---> ---Windows detected mouse movement-->You must restart to save changes Y/N--- 

    On Monday, May 8, 2017 9:46 PM, Rocologo <notifications@github.com> wrote:
 

 Ahh, it looks like you have a name conflict. Try again using mobhunt instead of mh. Enable debug, run the command and show me the log.I did not realize "---Windows detected mouse movement-->You must restart to save changes Y/N---" was from your log, i have never seen this error before.—

**Comment by Rocologo** [comment]
You have lost me now ?????

I need the debug information in the server log to help you?

**Comment by Rocologo** [comment]
I cant fix this with more information from you?

**Comment by spamattack** [comment]
There isn't anything else that is produced in debug mode or otherwise . I told you the system responded with unknown user in all instances. Is there a possibility that debug mode is broken? Who knows but it produces no other info

**Comment by Rocologo** [comment]
No, the debug mode works perfect. But I think you have two plugins which conflicts. 

So lets do this another way. Open config.yml and find "kill_debug" and make sure that its true. Then restart your server, run "/mobhunt head drop playername"  and give me the complete full log on restart, so i can see all the debug information. Then I hope I can see whats wrong.

**Comment by Rocologo** [comment]
Please test build 381 on my Jenkins server
https://fractal.lindegaard.one:8181/job/MobHunting/

I hope the head problem is fixed now. If the head does not look ok , please try to place it on the ground and break it again.

**Comment by Rocologo** [comment]
Please try the heads in V4.9.3 

I found and fixed a bug.

**Comment by spamattack** [comment]
Yes yes!! its a Steve head when you get it but after placing it , it becomes the head of the person it came from!!!bravo good job!!!!!!! ---Windows detected mouse movement-->You must restart to save changes Y/N--- 

    On Tuesday, May 30, 2017 11:49 PM, Rocologo <notifications@github.com> wrote:
 

 Please try the heads in V4.9.3I found and fixed a bug.—

**Comment by Rocologo** [comment]
Finally. I cant change that it is a Steve head in the beginning. This is a Minecraft issue. Place the head a known workaround, but I think that if you keep the head in the inventory it will change after some time too.

I close this ticket now.
