### ISSUE TITLE
A little problem——mypet?

### ISSUE THREAD

**Issue by BenLiHao** [Rocologo/MobHunting#214]
`[12:59:44 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.7.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1078) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:932) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityEnderman.damageEntity(EntityEnderman.java:276) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.attack(EntityMyPet.java:342) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.types.EntityMyPolarBear.attack(EntityMyPolarBear.java:88) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:115) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1007) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.n(EntityMyPet.java:939) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1892) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.A_(EntityMyPet.java:1160) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1653) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.World.g(World.java:1628) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1454) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
[12:59:45 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.7.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1078) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:932) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityEnderman.damageEntity(EntityEnderman.java:276) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.attack(EntityMyPet.java:342) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.types.EntityMyPolarBear.attack(EntityMyPolarBear.java:88) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:115) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1007) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.n(EntityMyPet.java:939) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1892) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.A_(EntityMyPet.java:1160) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1653) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.World.g(World.java:1628) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1454) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
`

**Comment by Rocologo** [comment]
Try upgrading SpigotMC. 

I don't have access to MyPet Premium 2.3.4. I can only test with 2.2.9 & 2.3.0-SNAPSHOT and I cant replicate the error. It a strange error it looks mostly like an error in MyPet or Spigot.

**Comment by Rocologo** [comment]
Same bug https://github.com/Rocologo/MobHunting/issues/210

**Comment by BenLiHao** [comment]
Ok, thank you, i go to test and update SpigotMC

**Comment by Rocologo** [comment]
Please test this snapshot

https://fractal.lindegaard.one:8181/job/MobHunting/345/
