### ISSUE TITLE
EntityDeathEvent EventException

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#220]
Spigot 1.11.2, MH 4.8.0
MyPet is not installed.

Quite a few log errors. Example:
> [13:23:55 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.8.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityWolf.B(EntityWolf.java:237) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:658) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityAnimal.n(EntityAnimal.java:24) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityWolf.n(EntityWolf.java:152) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.EntityWolf.A_(EntityWolf.java:167) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: de/Keyle/MyPet/api/entity/MyPetBukkitEntity
        at one.lindegaard.MobHunting.compatibility.MyPetCompat.getMyPetOwner(MyPetCompat.java:81) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.getPlayer(MobHuntingManager.java:1670) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:794) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar-2017-04-25-1238:git-Spigot-38ddb34-c19c293]
        ... 28 more

**Comment by Rocologo** [comment]
I made a stupid small error in 4.8.0 which caused this error. I made MyPet hard depended.
