### ISSUE TITLE
Mob Hunting with MythicMobs

### ISSUE THREAD

**Issue by zonprox** [Rocologo/MobHunting#23]
Could not pass event MythicMobSpawnEvent to MobHunting v2.8.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-944aa20-d39a750]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-944aa20-d39a750]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-944aa20-d39a750]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.elseland.xikage.MythicMobs.Mobs.MythicMob.spawn(MythicMob.java:620) [MythicMobs-2.4.0.jar:?]
	at net.elseland.xikage.MythicMobs.Mobs.MobSpawner.SpawnMythicMob(MobSpawner.java:35) [MythicMobs-2.4.0.jar:?]
	at net.elseland.xikage.MythicMobs.Mobs.MobSpawner.SpawnMythicMob(MobSpawner.java:24) [MythicMobs-2.4.0.jar:?]
	at net.elseland.xikage.MythicMobs.Adapters.Bukkit.Commands.MobCommands.cmdMobSpawn(MobCommands.java:157) [MythicMobs-2.4.0.jar:?]
	at net.elseland.xikage.MythicMobs.Adapters.Bukkit.Commands.MobCommands.parseCommands(MobCommands.java:56) [MythicMobs-2.4.0.jar:?]
	at net.elseland.xikage.MythicMobs.Adapters.Bukkit.Commands.CommandHandler.onCommand(CommandHandler.java:48) [MythicMobs-2.4.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-944aa20-d39a750]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-944aa20-d39a750]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-944aa20-d39a750]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-944aa20-d39a750]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-944aa20-d39a750]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoSuchFieldError: MobName
	at one.lindegaard.MobHunting.compatability.MythicMobsCompat.onMythicMobSpawnEvent(MythicMobsCompat.java:194) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-944aa20-d39a750]
	... 25 more

I've install MythicMobs and Mob Hunting and get this error

**Comment by Rocologo** [comment]
Update MobHunting before reporting bugs. This one is fixed in V2.8.6.
