### ISSUE TITLE
Could not pass EntityDeathEvent.... Caused by integer cannot be cast to string

### ISSUE THREAD

**Issue by Tasmainia300** [Rocologo/MobHunting#234]
I keep getting this console error when I kill a mob in my server. It doesn't award me any money either. This was also happening in v4.9.2, I downloaded 4.9.3 to see if it would fix itself.

[19:41:53 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.9.3-SNAPSHOT-B380
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1069) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:923) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1158) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1509) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at one.lindegaard.MobHunting.modifier.DifficultyBonus.doesApply(DifficultyBonus.java:72) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1369) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        ... 20 more

**Comment by Rocologo** [comment]
I think you have made an error in your config.yml in the difficulty - multiplier section. Please the me see what you have entered?

**Comment by Tasmainia300** [comment]
OH! I just looked at it and I accidentally put 1 as the hard mode multiplier rather than '1' lol. I had been working on yaml all day yesterday so I guess by the time it happened my brain was too fried to figure it out. Thanks for replying and thanks for pointing me to the issue! It's working now.
