### ISSUE TITLE
PaperSpigot #1113+ and MH not working

### ISSUE THREAD

**Issue by vilgrar** [Rocologo/MobHunting#252]
Because I intend to upgrade my server to 1.12 in future, I ran some tests and found out that PaperSpigot #1113 [https://ci.destroystokyo.com/job/PaperSpigot/1113/] and beyond crashes MobHunting. All prior 1.12 releases (#1105 - #1112) have no problem at all.

MobHunting wasn't alone on this. MyWarp and MyPet would also work fine before but start crashing from #1113. I'm not sure whether I should report this to all respective plugin programmers or to the PaperSpigot team?

Anyhow, here's the error.

[11:33:07 INFO]: [MobHunting] Enabling MobHunting v4.9.5-SNAPSHOT-B407
[11:33:07 ERROR]: Error occurred while enabling MobHunting v4.9.5-SNAPSHOT-B407 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/jline/internal/InputStreamReader
        at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:123) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1123]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1123]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1123]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.12.jar:git-Paper-1123]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.12.jar:git-Paper-1123]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1123]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1123]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1123]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1123]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1123]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12.jar:git-Paper-1123]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1123]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 12 more

**Comment by Rocologo** [comment]
First of all, you should chance to newest snapshot. Build 407 has lag problems when you kill a mob.

And about the bug, Im not sure if Paper can do anything about this and why it suddenly comes after we have moved to MC1.12, its probaly because Mojang have made alot of essential changes in their code, and they have removed a lot old code. On the other hand Spigot MC does not have this problem, so it might help that you posted a ticket at the PaperClip team. 

Im not sure how I remove this bug, but I have seen an update for some of these plugins I use, so I will contact the dev and ask what he did.

**Comment by Rocologo** [comment]
PS. 

When you get these bugs, you should always focus on the last part "Caused by:" 

Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12.jar:git-Paper-1123]

It tells you where in the code it actually failed. In this case "PluginClassLoader.java:92" in the JAR "patched_1.12.jar"

**Comment by Rocologo** [comment]
https://github.com/Ste3et/FurnitureLib/issues/27#issuecomment-307868622

**Comment by vilgrar** [comment]
I'm not using the developer's build on my real server. Everything works pretty fine at 4.9.4 but will update to 4.9.5 when you release it.

To clarify once more, PaperSpigot has released 1.12 server versions that DO work without errors. #1105 - #1112 (8 releases) didn't have those problems. #1113 - #1123 however, do. So whatever they added in #1113 ("Improve console implementation") is what's causing the error. Well, I guess it wouldn't hurt to post a ticket.

Could've sworn I used B414 on my test server, but B414 says pretty much the same thing.

Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12.jar:git-Paper-1113]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1113]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 12 more

**Comment by Rocologo** [comment]
I think I have fixed this problem in Build 413. 
https://fractal.lindegaard.one:8181/job/MobHunting/

I replaced org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader 
with java.io.InputStreamreader

Im still at work, so Im not able to start my PaperClip server and as far as I remember I have not made a Paper 1.12 test server yet. If you can help testing it would be nice.

**Comment by Rocologo** [comment]
Build 414 is compiled 2 min ago. So Im sure you have not tested that :-)

**Comment by Rocologo** [comment]
This ticket helped me solving the problem. (If any other developer have the same problem)

**Comment by vilgrar** [comment]
414 fixed the problem! No error messages!

**Comment by Rocologo** [comment]
Thanks, I will release v.4.9.5 tonight, when Im back from work :-) 

And once again. THANKS for your great help with the testing. It is very useful!

**Comment by vilgrar** [comment]
Glad to help. Well, it benefits me as well =)

414 seems to work fine on 1.11.2 as well.

**Comment by Rocologo** [comment]
Released V4.9.5
