### ISSUE TITLE
EventException when Right and Left clicking.

### ISSUE THREAD

**Issue by Phonon1** [Rocologo/MobHunting#255]
Hi. I have an issue with your awesome plugin. It seems to work perfectly, but when I check the console, it shows an Error whenever a player uses right click or left click on an object for interaction (doors, buttons...) or simply on a block for destroying it or placing it. This would be totally ok, as it seems everything is working fine, but it is generating ridiculously long console logs.
I am running Spigot 1.9, on Java 8 on a paid Server.pro server, in case it can help.

Here is a fragment of the log. If I can provide something else that can help, just tell me. Thanks.

```
[17:00:36 ERROR]: Could not pass event PlayerInteractEvent to MobHunting v4.9.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:784) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
        at one.lindegaard.MobHunting.npc.MasterMobHunterSign.onPlayerInteractEvent(MasterMobHunterSign.java:312) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        ... 18 more
[17:00:37 ERROR]: Could not pass event PlayerInteractEvent to MobHunting v4.9.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:840) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
        at one.lindegaard.MobHunting.npc.MasterMobHunterSign.onPlayerInteractEvent(MasterMobHunterSign.java:312) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        ... 17 more
[17:00:37 ERROR]: Could not pass event PlayerInteractEvent to MobHunting v4.9.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:784) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
        at one.lindegaard.MobHunting.npc.MasterMobHunterSign.onPlayerInteractEvent(MasterMobHunterSign.java:312) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        ... 18 more
[17:00:37 ERROR]: Could not pass event PlayerInteractEvent to MobHunting v4.9.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:840) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
        at one.lindegaard.MobHunting.npc.MasterMobHunterSign.onPlayerInteractEvent(MasterMobHunterSign.java:312) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        ... 17 more
```

**Comment by Rocologo** [comment]
This is fixed in build 255
http://jenkins.lindegaard.one:8180/job/MobHunting/
