### ISSUE TITLE
Exception when blacklist area mob got killed

### ISSUE THREAD

**Issue by DawgZilla** [Rocologo/MobHunting#266]
Hey,
I get for every killed mob in a blacklisted area this "little" exception 

‎20‎:‎43‎:‎47
Could not pass event EntityDeathEvent to MobHunting v4.9.5
Console 
‎11‎.‎07‎.‎2017 ‎20‎:‎43‎:‎47

‎20‎:‎43‎:‎47
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1109) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.EntityEnderman.damageEntity(EntityEnderman.java:276) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1030) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1609) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1298) ~[?:?]
at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
... 22 more

Are there ways to fix/hide this ?

Great plugin by the way. Love it!

**Comment by Rocologo** [comment]
Tell me which version of protocollib you are ising and then try upgrading it to newest version. I Think its outdated
