### ISSUE TITLE
Warn on Spigot 1.12 and Java 8.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#269]
[20:11:22] [Server thread/WARN]: [MobHunting] Task #469 for MobHunting v5.0.0 generated an exception
java.lang.IllegalArgumentException: advancement
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:1449) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at io.chazza.advancementapi.AdvancementAPI.grant(AdvancementAPI.java:194) ~[?:?]
	at io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(AdvancementManager.java:127) ~[?:?]
	at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:640) ~[?:?]
	at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:578) ~[?:?]
	at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:324) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[20:11:22] [Server thread/WARN]: [MobHunting] Task #471 for MobHunting v5.0.0 generated an exception
java.lang.IllegalArgumentException: advancement
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:1449) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at io.chazza.advancementapi.AdvancementAPI.grant(AdvancementAPI.java:194) ~[?:?]
	at io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(AdvancementManager.java:127) ~[?:?]
	at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:640) ~[?:?]
	at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:578) ~[?:?]
	at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:324) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Rocologo** [comment]
Yes, this is cause by the new Advancement features, I dont know how to fix this at the moment, but you can disable MobHunting integration in the newest snapshot.  Build 432 or newer. Check "disable_mobhunting_advancements" in config.yml

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
I need your help to get more information to solve this. I have added some debug information to the code which fails. 

Please use build 435 or newer : http://jenkins.lindegaard.one:8180/job/MobHunting/
and then enable debug using "/mh debug" and let me see the information in the serverlog when this error is thrown?

**Comment by Rocologo** [comment]
No answer, i close the ticket....
