### ISSUE TITLE
error Could not pass event EntityDamageByEntityEvent to MobHunting v5.0.8

### ISSUE THREAD

**Issue by tygh78071388** [Rocologo/MobHunting#292]
```
 Could not pass event EntityDamageByEntityEvent to MobHunting v5.0.8
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:578) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:610) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1330) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:872) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:531) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityArrow.a(EntityArrow.java:295) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityArrow.A_(EntityArrow.java:203) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityTippedArrow.A_(EntityTippedArrow.java:86) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1740) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1715) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1532) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:621) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:907) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
```
Do not know what causes it...
PaperSpigot-1.11.2-b1104

**Comment by Rocologo** [comment]
you need to post the last part of the error text - starting with "Caused by" I need this information to fix the bug.

**Comment by tygh78071388** [comment]
Caused by: java.lang.NullPointerException

sorry XD

**Comment by Rocologo** [comment]
The FULL error text, it tells me line numbers in my code which I need to solve the bug ;-)
