### ISSUE TITLE
NPE with holograms on startup

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#296]
Spigot 1.12.1
MH 5.0.9-SNAPSHOT-B462
Holograms 2.5.0-SNAPSHOT

Create hologram.  Looks good.
Stop server.
Start server.
Hologram is not read in, and once a minute ...
```
[16:02:54] [Server thread/WARN]: [MobHunting] Task #3242 for MobHunting v5.0.9-SNAPSHOT-B462 generated an exception
java.lang.NullPointerException: null
        at com.sainttx.holograms.api.line.TextLine.setText(TextLine.java:69) ~[?:?]
        at one.lindegaard.MobHunting.leaderboard.HologramLeaderboard.refresh(HologramLeaderboard.java:114) ~[?:?]
        at one.lindegaard.MobHunting.leaderboard.HologramLeaderboard.onCompleted(HologramLeaderboard.java:226) ~[?:?]
        at one.lindegaard.MobHunting.leaderboard.HologramLeaderboard.onCompleted(HologramLeaderboard.java:32) ~[?:?]
        at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:328) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1.jar-2017-09-09-0846:git-Spigot-da42974-876d22c]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.1.jar-2017-09-09-0846:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.1.jar-2017-09-09-0846:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar-2017-09-09-0846:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar-2017-09-09-0846:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar-2017-09-09-0846:git-Spigot-da42974-876d22c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

[hologram-leaderboards.yml.txt](https://github.com/Rocologo/MobHunting/files/1296210/hologram-leaderboards.yml.txt)

**Comment by Rocologo** [comment]
Delete your hologram-leaderboards.yml file and try build 463, 

if you get the above error again, please let me see your hologram-leaderboard.yml file

**Comment by SlimeDog** [comment]
Spigot 1.12.1 latest
MH 5.0.9-SNAPSHOT-B464
Holograms 2.5.0-SNAPSHOT

```
/mh hologram create bonus1 Total_Coins AllTime 7
```
No player rows are displayed. They were displayed with MH 5.0.0-SNAPSHOT-B462.
```
/mh hologram update bonus1
```
New title is displayed. No player data are displayed.
```
/mh hologram delete bonus1
```
Title is still displayed. hologram-leaderboards.yml is empty (except for header comments).

[hologram-leaderboards.yml.txt](https://github.com/Rocologo/MobHunting/files/1297708/hologram-leaderboards.yml.txt)

**Comment by SlimeDog** [comment]
The problem seems to be with Holograms plugin. Judging from the comments in that forum, holograms are not persistent across reboots with Spigot 1.12.x.

Switching to HolographicDisplays plugin, things are working much better. Small glitch: After editing the formats and **/mh hologram update**, the previous hologram remains until reboot. Perhaps this can be managed through the HD API, or maybe not. Livable, unless one wants dynamic holographic displays.

**Comment by SlimeDog** [comment]
Spigot 1.12.1
MH 5.0.9-SNAPSHOT-B465
Holograms 2.5.0-SNAPSHOT and (separately) HolographicDisplays 2.2.6

Both work correctly. I have no idea what transpired in previous tests.

I prefer HolographicDisplays, so I'll be testing that unless Holograms is specifically requested.
