### ISSUE TITLE
issues with 3.0.0 on 1.9-1.9.2

### ISSUE THREAD

**Issue by XxthedarkkingxX** [Rocologo/MobHunting#30]
[23:26:58] [Server thread/ERROR]: Could not load 'plugins\MobHunting3.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:293) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.<init>(CraftServer.java:255) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at net.minecraft.server.v1_9_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at net.minecraft.server.v1_9_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:182) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_77]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_77]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.9.jar:git-Bukkit-8269b99]
	... 9 more

now it says 9 more but that is the only error it throws at me.

i also get the same error running it on 1.9.2

**Comment by Rocologo** [comment]
It looks like you need to update to latest version Spigot/Craftbukkit. V3.0.0 is compiled with newest version  1.9.4 of Minecraft but it still support minecraft 1.7.9 - 1.9.4. Try using Buildtools to update Spigot/Craftbukkit.

**Comment by Rocologo** [comment]
Remember to use newest version of buildtools too...

**Comment by Rocologo** [comment]
Ps. I running v3.0.0. On my own 1.9.2 server mc.lindegaard.one so i known it works ☺

**Comment by Rocologo** [comment]
Closed because no action from reporter...
