### ISSUE TITLE
Once again MySQL connection issue with new version

### ISSUE THREAD

**Issue by c0mput3** [Rocologo/MobHunting#31]
Here we are again, Version 3 fails to connect to the MySQL backend.

[04:42:04] [Server thread/WARN]: [AutoSaveWorld] Plugin MobHunting attempted to establish connection socket://127.0.0.1:3306 in main server thread
[04:42:04] [Server thread/WARN]: one.lindegaard.MobHunting.storage.DataStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: REFERENCES command denied to user 'mcadmin'@'localhost' for table 'mh_Players'
[04:42:04] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:130)
[04:42:04] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:174)
[04:42:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[04:42:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[04:42:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[04:42:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[04:42:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[04:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[04:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[04:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[04:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[04:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[04:42:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[04:42:04] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: REFERENCES command denied to user 'mcadmin'@'localhost' for table 'mh_Players'
[04:42:04] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:42:04] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:42:04] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:42:04] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1541)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2605)
[04:42:04] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1469)
[04:42:04] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.MySQLDataStore.setupTables(MySQLDataStore.java:246)
[04:42:04] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:126)
[04:42:04] [Server thread/WARN]: 	... 12 more

if you would like help testing your plugin before release, i would be happy to help.

**Comment by Rocologo** [comment]
I agree. I have to find a way to get the plugin tested before a release. And I need help. 

I'm in Milan the next three days. Without a computer and with my girlfriend. So I can't fix it until Monday.  

In this case I can see it is the creation of a table in the mysql database. My problem is that I don't have a mysql test database where I can scratch everything and make a fresh start and test it. I need to find a solution to that.

**Comment by c0mput3** [comment]
Hey Rocologo,

Enjoy your trip to Milan, a wonder city in a fabulous country.
Upon your return and at one's earliest convenience i would be happy to offer you any resources you may need to assist you further.

**Comment by Rocologo** [comment]
Back at the hotel I googled your problem, I would like you to check mcadmin@localhost permission. Normally you should grant all permissions but the error text say that you mcadmin dont have REFERENCES permission?

**Comment by c0mput3** [comment]
There is nothing wrong with the permissions for that user account.

**Comment by Rocologo** [comment]
Ok. It was just a though. I will create a test Mysql database and test creation of tables when I'm back home.


Sent from my Samsung device

-------- Original message --------

**Comment by c0mput3** [comment]
Yea no worries, enjoy your short break.

**Comment by Rocologo** [comment]
Hi again. Back home.

I spend two hours enabling my MySQL Server for remote connections, so my test-server could access the MySQL server on my production server. I had to change localhost to internal IP address in all my plugins on the PROD server and I had to reconfigure Multicraft too.

I am not able to test MySQL features on a test-server. First thing was of cause to start the server with an empty database and check that all tables was created. 

Everything went fine, all tables were created and I could start the game and kill mobs and killings was counted exactly like it should.

SO now we are back to your problem. I cant reproduce the error you had and when googeling your problem I still think you have forgotten to grant all access to the database. Notice the "REFERENCES" is a special permission.

**Comment by Rocologo** [comment]
Do you still have this error?

**Comment by c0mput3** [comment]
I've dropped the plugin for now, as all other plugins work fine with Mysql

**Comment by teozfrank** [comment]
REFERENCES command denied to user 'mcadmin'@'localhost' for table 'mh_Players'

MySQL user permission error, not an error of the plugin itself, grant the user full access to the database ->

GRANT ALL ON databasename.* TO 'mcadmin'@'localhost'

Where databasename is the name of the database.

**Comment by c0mput3** [comment]
ok dude i'll give it a go, when i have the time.

Just i don't have any problems with any other plugins using mysql, and that
user account

**Comment by Rocologo** [comment]
Well do you know if the other plugins uses REFERENCES ? If they does they will work fine without the permission to use if. 
Try to run sql command "grant references on <db> to <dbaname> "
Or "grant all on <db> to <dba>"


Sent from Samsung tablet.



-------- Original message --------

**Comment by Rocologo** [comment]
Or you can swicth to sqlite where you dont have permission problems

**Comment by Rocologo** [comment]
Okay. I close the ticket now. And open the ticket if you decide to use MobHunting again.
