### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by zigaliro** [Rocologo/MobHunting#333]
[16:13:17] [Server thread/INFO]: Legendex555 issued server command: /mobhunt top Zombie_Kills alltime 5
[16:13:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mobhunt' in plugin MobHunting v5.2.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.commands.TopCommand.onCommand(TopCommand.java:97) ~[?:?]
	at one.lindegaard.MobHunting.commands.CommandDispatcher.onCommand(CommandDispatcher.java:98) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	... 15 more

Why is that error?

**Comment by Rocologo** [comment]
This is very strange... I tested the exactly same command on my own server... no problems...

**Comment by Rocologo** [comment]
Which spigot/Minecraft version does you run?

**Comment by Rocologo** [comment]
Have you made your own translation?

**Comment by Rocologo** [comment]
No answers... Ticket closed...
