### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by FliXPB** [Rocologo/MobHunting#341]
Version 5.3.5 spamming this in console

> [15:20:39 ERROR]: Could not pass event InventoryClickEvent to MobHunting v5.3.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Bukkit-ab09b27]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-ab09b27]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Bukkit-ab09b27]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1820) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-ab09b27]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit.jar:git-Bukkit-ab09b27]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit.jar:git-Bukkit-ab09b27]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
        at one.lindegaard.MobHunting.rewards.RewardListeners.onInventoryClickReward(RewardListeners.java:399) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit.jar:git-Bukkit-ab09b27]
        ... 15 more

Using latest version of bukkit on a linux VM

**Comment by Rocologo** [comment]
Bukkit? 

Please type /version in the console and give me the result?

**Comment by Rocologo** [comment]
You need CraftBukkit, SpigotMc or PaperSpigot. You can not use Bukkit

**Comment by FliXPB** [comment]
Sorry, brain wasn't functioning, am using CraftBukkit.

**Comment by Rocologo** [comment]
Some must be wrong with your server. 

org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()

has existed for a long time, and this is way I think something is wrong. 

Please paste your server.log (use pastebin.com) so I can check if the plugin starts as it should.

**Comment by FliXPB** [comment]
https://pastebin.com/hqx88cKW

**Comment by Rocologo** [comment]
Bug confirmed. I am able to reproduce on my TestServer now...

**Comment by Rocologo** [comment]
It works on SpigotMC 1.12.2 but not on CraftBukkit 1.12.2 i will have to find a way to solve this...

**Comment by Rocologo** [comment]
This is fixed in V5.3.6
