### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by Tippolo** [Rocologo/MobHunting#344]
WARN
 
11/01/2018 18:11:58

18:11:58

one.lindegaard.MobHunting.storage.DataStoreException: java.sql.BatchUpdateException: Unknown column 'TEXTURE' in 'field list'
at one.lindegaard.MobHunting.storage.DatabaseDataStore.insertPlayerSettings(DatabaseDataStore.java:1102)
at one.lindegaard.MobHunting.storage.asynch.PlayerSettingsRetrieverTask.run(PlayerSettingsRetrieverTask.java:34)
at one.lindegaard.MobHunting.storage.asynch.PlayerSettingsRetrieverTask.run(PlayerSettingsRetrieverTask.java:15)
at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:403)
Caused by: java.sql.BatchUpdateException: Unknown column 'TEXTURE' in 'field list'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.Util.getInstance(Util.java:408)
at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
at one.lindegaard.MobHunting.storage.DatabaseDataStore.insertPlayerSettings(DatabaseDataStore.java:1095)
... 3 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'TEXTURE' in 'field list'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.Util.getInstance(Util.java:408)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
... 6 more

**Comment by Rocologo** [comment]
I need more details...

How did you end up in this situation?

Is it first time you install mobhunting or are you upgrading?

**Comment by Rocologo** [comment]
Try setting "database_version: 0" in your config.yml and restart your server.

This will force the plugin to detect version number. If TEXTURE is not found it should be created automatically.

**Comment by Tippolo** [comment]
This is a fresh install, when a player join the server I receive this warn and then no data stored in mysql.
With sqlite the same error.
Try the last  solution set "database_version: 0" and restart, no error in console when join the server.

Thank's a lot

**Comment by Rocologo** [comment]
Okay, Your problem was solved, but I guess I will have to test a fresh install and check whats wrong
