### ISSUE TITLE
Many errors in log with 3.0.2 InventoryCreativeEvent

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#37]
[22:53:12] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to MobHunting v3.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2001) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClick(AchievementManager.java:662) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	... 15 more
[22:53:12] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to MobHunting v3.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2001) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClick(AchievementManager.java:662) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	... 15 more
[23:06:59] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to MobHunting v3.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2001) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClick(AchievementManager.java:662) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	... 15 more
[23:07:00] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to MobHunting v3.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2001) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClick(AchievementManager.java:662) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	... 15 more
[23:17:00] [Server thread/INFO]: Peekaboo issued server command: /fly
[23:22:20] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to MobHunting v3.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2001) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClick(AchievementManager.java:662) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	... 15 more

**Comment by Rocologo** [comment]
This will be fixed in next release. Except for the spam this error doesnt matter. It happens when a player opens the new achievement gui and click on "nothing" outside the inventory.

**Comment by Rocologo** [comment]
Fixed in V3.0.3
