### ISSUE TITLE
sqlite error on player login - "no such table: mh_Bounties"

### ISSUE THREAD

**Issue by bc-hill** [Rocologo/MobHunting#370]
`07.03 19:21:26 [Server] WARN org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: mh_Bounties)
07.03 19:21:26 [Server] WARN at org.sqlite.core.DB.newSQLException(DB.java:909)
07.03 19:21:26 [Server] WARN at org.sqlite.core.DB.newSQLException(DB.java:921)
07.03 19:21:26 [Server] WARN at org.sqlite.core.DB.throwex(DB.java:886)
07.03 19:21:26 [Server] WARN at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
07.03 19:21:26 [Server] WARN at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
07.03 19:21:26 [Server] WARN at org.sqlite.core.DB.prepare(DB.java:227)
07.03 19:21:26 [Server] WARN at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
07.03 19:21:26 [Server] WARN at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
07.03 19:21:26 [Server] WARN at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
07.03 19:21:26 [Server] WARN at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
07.03 19:21:26 [Server] WARN at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
07.03 19:21:26 [Server] WARN at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
07.03 19:21:26 [Server] WARN at one.lindegaard.MobHunting.storage.SQLiteDataStore.openPreparedStatements(SQLiteDataStore.java:90)
07.03 19:21:26 [Server] WARN at one.lindegaard.MobHunting.storage.DatabaseDataStore.loadBounties(DatabaseDataStore.java:996)
07.03 19:21:26 [Server] WARN at one.lindegaard.MobHunting.storage.asynch.BountyRetrieverTask.run(BountyRetrieverTask.java:56)
07.03 19:21:26 [Server] WARN at one.lindegaard.MobHunting.storage.asynch.BountyRetrieverTask.run(BountyRetrieverTask.java:15)
07.03 19:21:26 [Server] WARN at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:402)
`

Occurs with latest release, and build 599.  Unsure if it actually impacts anything.
Let me know if you need more data!

**Comment by bc-hill** [comment]
Sorry, I just realized that this is irrelevant to me, as I did not mean to have bounties enabled.

**Comment by bc-hill** [comment]
Developer provided fix for this, in Discord:
"if you are missing this table you just set database_version to 0 in config.yml and restart your server then it will be created."
