### ISSUE TITLE
Error with StackMob

### ISSUE THREAD

**Issue by MCTyler** [Rocologo/MobHunting#372]
If I enable Step kill in StackMob, it kills the entire Stack and throws this error...
[19:58:37 ERROR]: Could not pass event EntityDeathEvent to MobHunting v5.5.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1114) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityPig.die(EntityPig.java:136) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1790) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor286.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        ... 21 more

**Comment by Rocologo** [comment]
Im pretty sure this is same bug as your other ticket https://github.com/Rocologo/MobHunting/issues/373

please test the newest snapshot and let me know if it works.

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment]
fixed in 5.5.7
