### ISSUE TITLE
Error on Pvp Death Event

### ISSUE THREAD

**Issue by MCTyler** [Rocologo/MobHunting#373]
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1790) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        ... 22 more

**Comment by Rocologo** [comment]
Please show me your PVP section (pvp settings)

**Comment by MCTyler** [comment]
# ########################################################################
# Pvp rewards
# ########################################################################
# Pvp configuration. Set pvp_allowed = true if you want give the players a reward when they kill eachother.
# You can alsp run a console command when this happens to give the player a reward or punish him.
# You can you the following variables {player},{world},{killed_player}.
# An example could be to give the player permission to fly 
# for 1 hour or use give command to the player items.
# You can also specify the message send to the player.
# You can run many console commands on each line, each command
# must be separated by |
pvp:
  player:

    # Set pvpAllowed=false to disable rewards on killing other players.
    pvp_allowed: true

    # Set rob_from_victim=true to steal from the victim or 
    # rob_from_victim=false to get the reward money from the server.
    rob_from_victim: true

    # Write the message to the killer, describing the reward / console commands
    message: You got {killed_player}'s skull

    # The kill prize can be a number to steal x dollars from the killed player,
    # or it can be a cut in percent of his balance. Rob from victiom is about where the money comes from.
    # If FALSE the money comes from from the server, if TRUE the money comes from the dead player.
    # If you dont want the player to get any money for PVP kills, you MUST set pvp_kill_prize: 0
    money:
      amount: 1.0%
      chance: 1.0

    # One or more console commands to be run when a player kills another player.
    commands:
    - chance: '0.5'
      cmd: ''

    # Drop a head of the killed player
    head:
      drophead: true

      # The Head price if you want playerheads to have a value like the bag of gold.
      value: '10'
      chance: 1.0
      message: You got {killed}'s skull

**Comment by MCTyler** [comment]
Did that help?

**Comment by Rocologo** [comment]
Im still not 100% sure you get this bug. (I dont get the bug myself) but I made a fix, so please test  snapshot 600 or newer
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment]
fixed in 5.5.7
