### ISSUE TITLE
MobHunting 5.5.6 Missing Mh_Bounties in sql database

### ISSUE THREAD

**Issue by CampingSteve** [Rocologo/MobHunting#377]
on a clean install of new plugin missing mh_bounties

 CampingSteve[/127.0.0.1:57895] logged in with entity id 395 at ([world]17.41896677229875, 67.0, 174.67867388841074)
[16:32:29 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: mh_Bounties)
[16:32:29 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:909)
[16:32:29 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:921)
[16:32:29 WARN]:        at org.sqlite.core.DB.throwex(DB.java:886)
[16:32:29 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[16:32:29 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[16:32:29 WARN]:        at org.sqlite.core.DB.prepare(DB.java:227)
[16:32:29 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
[16:32:29 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[16:32:29 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
[16:32:29 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
[16:32:29 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
[16:32:29 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
[16:32:29 WARN]:        at one.lindegaard.MobHunting.storage.SQLiteDataStore.openPreparedStatements(SQLiteDataStore.java:90)
[16:32:29 WARN]:        at one.lindegaard.MobHunting.storage.DatabaseDataStore.loadBounties(DatabaseDataStore.java:996)
[16:32:29 WARN]:        at one.lindegaard.MobHunting.storage.asynch.BountyRetrieverTask.run(BountyRetrieverTask.java:56)
[16:32:29 WARN]:        at one.lindegaard.MobHunting.storage.asynch.BountyRetrieverTask.run(BountyRetrieverTask.java:15)
[16:32:29 WARN]:        at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:402)
>

**Comment by Rocologo** [comment]
I have found the bug. I will make a new release because of this bug.

V5.5.7
