### ISSUE TITLE
Error on unload

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#38]
Maybe you need a cancelTask in your ondisable()
-› pm unload MobHunting
[03:27:45 INFO]: [MobHunting] Disabling MobHunting v3.0.2
[03:27:45 WARN]: Exception in thread "MH TaskThread" 
[03:27:45 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[03:27:45 WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:400)
[03:27:45 WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123)
[03:27:45 WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:106)
[03:27:45 WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTask(CraftScheduler.java:89)
[03:27:45 WARN]: at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:409)

**Comment by FlashLight34** [comment]
And that freeze my server!

**Comment by FlashLight34** [comment]
this error not appear with 3.0.1

**Comment by Rocologo** [comment]
I think i have to check if im missing a database close statement somewhere. This could cause this problem. I will also check if i need to deregister something. But I thinkit happens if there is unsaved playerstats when you close your server.

**Comment by Rocologo** [comment]
Fixed in V3.0.3 ( I hope)
