### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#389]
[13:31:42] [Craft Scheduler Thread - 37/WARN]: [MobHunting] Plugin MobHunting v5.6.0 generated an exception while executing task 12474
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463) ~[?:1.8.0_72]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461) ~[?:1.8.0_72]
	at one.lindegaard.MobHunting.Messages$1.run(Messages.java:512) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1370]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1370]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1370]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Rocologo** [comment]
Please help test build 613
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
Fixed in v5.6.1
