### ISSUE TITLE
Right-Click or Left-Click Skull Could not pass event PlayerInteractEvent to MobHunting

### ISSUE THREAD

**Issue by amrhfy** [Rocologo/MobHunting#391]
[21:08:49] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MobHunting v5.6.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.rewards.RewardListeners.onPlayerInteractEvent(RewardListeners.java:450) ~[MobHunting.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
	... 18 more

**Comment by Rocologo** [comment]
What are you clicking on?

**Comment by amrhfy** [comment]
im clicking on custom textured heads from CustomHeads plugin. ive also tried other custom head plugin such as Heads and Head Database. its print out the same error :)

**Comment by amrhfy** [comment]
yes im running 1.8.8 paperspigot, hope i get a fix soon

**Comment by amrhfy** [comment]
so how it is?

**Comment by Rocologo** [comment]
I have a job where I get paid to work you know.... this is only in my spare time, a hobby... so please be patient...

**Comment by Rocologo** [comment]
Try this build: https://fractal.lindegaard.one:8181/job/MobHunting/618/

**Comment by amrhfy** [comment]
ill try later but dont close the issues yet :)

**Comment by Rocologo** [comment]
Bum. Any new comments?

**Comment by amrhfy** [comment]
just test the build n its working fine.. hope u cn fix this issue on latest ver soon :)

**Comment by Rocologo** [comment]
But didnt you write it was fixed?

**Comment by amrhfy** [comment]
yes it is, but i hope can get the fix on the latest build cause i wnt all the ne feature

**Comment by Rocologo** [comment]
Which new festures?

**Comment by amrhfy** [comment]
database reset

**Comment by Rocologo** [comment]
But it is already possible??? Just write /mh database and press <TAB>  5 times

**Comment by Rocologo** [comment]
Press tab key 5 times

**Comment by Rocologo** [comment]
The help text has been added to newest snapshot, build >621

https://fractal.lindegaard.one:8181/
