### ISSUE TITLE
Unresolved Issue: MobHunter V2.8.1 and Mysql - Errors when players connect.

### ISSUE THREAD

**Issue by c0mput3** [Rocologo/MobHunting#4]
Problem still persist, When players connect to the server the follow error is disabled in the logs.
If i configure the plugin to use sqlite, there is no error.

Please advise.

12:46:40] [Server thread/WARN]: java.sql.SQLException: No value specified for parameter 1
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2205)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2185)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2115)
[12:46:40] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1936)
[12:46:40] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.DatabaseDataStore.getPlayerSettings(DatabaseDataStore.java:188)
[12:46:40] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.DataStoreManager.getPlayerData(DataStoreManager.java:315)
[12:46:40] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.MobHunting.onPlayerJoin(MobHunting.java:1392)
[12:46:40] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:46:40] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:46:40] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:46:40] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:46:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[12:46:40] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:46:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:46:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[12:46:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[12:46:40] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:46:40] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MobHunting v2.8.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at au.com.mineauz.MobHunting.MobHunting.onPlayerJoin(MobHunting.java:1392) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	... 14 more

**Comment by Rocologo** [comment]
Fixed in v2.8.4
