### ISSUE TITLE
Error for Skull

### ISSUE THREAD

**Issue by downboy** [Rocologo/MobHunting#400]
Spigot 1.12
Mobhunting version: 5.6.2
**Fresh install**

`> [19:51:01 WARN]: [MobHunting] Task #300 for MobHunting v5.6.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.SkullMeta.setOwningPlayer(Lorg/bukkit/OfflinePlayer;)Z
at one.lindegaard.MobHunting.rewards.CustomItems.getPlayerHeadOwningPlayer(CustomItems.java:235) ~[?:?]
at one.lindegaard.MobHunting.rewards.CustomItems.getPlayerHead(CustomItems.java:112) ~[?:?]
at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:127) ~[?:?]
at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:114) ~[?:?]
at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:340) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by Rocologo** [comment]
It looks like you use an old version of SpigotMC?

What is the output when you type /version ?

**Comment by downboy** [comment]
This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by Rocologo** [comment]
Yes never versions of 1.12.2 has this function"setOwningPlayer"
