### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by cdmvirt** [Rocologo/MobHunting#412]
[04:17:54 WARN]: one.lindegaard.MobHunting.storage.DataStoreException: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON DUPLICATE KEY UPDATE SET CREATED_DATE=1532765871259, END_DATE=1535357871259, ' at line 1
[04:17:54 WARN]: at one.lindegaard.MobHunting.storage.MySQLDataStore.saveBounties(MySQLDataStore.java:334)
[04:17:54 WARN]: at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:53)
[04:17:54 WARN]: at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:13)
[04:17:54 WARN]: at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:404)
[04:17:54 WARN]: Caused by: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON DUPLICATE KEY UPDATE SET CREATED_DATE=1532765871259, END_DATE=1535357871259, ' at line 1
[04:17:54 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:17:54 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:17:54 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:17:54 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:17:54 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:17:54 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
[04:17:54 WARN]: at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
[04:17:54 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
[04:17:54 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
[04:17:54 WARN]: at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[04:17:54 WARN]: at one.lindegaard.MobHunting.storage.MySQLDataStore.saveBounties(MySQLDataStore.java:327)
[04:17:54 WARN]: ... 3 more
[04:17:54 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON DUPLICATE KEY UPDATE SET CREATED_DATE=1532765871259, END_DATE=1535357871259, ' at line 1
[04:17:54 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:17:54 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:17:54 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:17:54 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:17:54 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:17:54 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
[04:17:54 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[04:17:54 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
[04:17:54 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
[04:17:54 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[04:17:54 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[04:17:54 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
[04:17:54 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[04:17:54 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[04:17:54 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
[04:17:54 WARN]: ... 6 more

**Comment by Rocologo** [comment]
Does this happen all the time or only once?

**Comment by Rocologo** [comment]
I think I found this bug.

Please test buil 682

https://fractal.lindegaard.one:8181/job/MobHunting/682/

**Comment by cdmvirt** [comment]
[04:37:28 INFO]: [MobHunting] Loading MobHunting v6.0.1-SNAPSHOT-B682
[04:37:29 ERROR]: [org.bukkit.craftbukkit.v1_13_R1.CraftServer] com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry; initializing MobHunting v6.0.1-SNAPSHOT-B682 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry;
at one.lindegaard.MobHunting.compatibility.WorldGuardHelper.registerFlag(WorldGuardHelper.java:117) ~[?:?]
at one.lindegaard.MobHunting.MobHunting.onLoad(MobHunting.java:99) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:325) ~[patched_1.13.jar:git-Paper-83]
at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:230) ~[patched_1.13.jar:git-Paper-83]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Rocologo** [comment]
Build 683 should work... sorry..

https://fractal.lindegaard.one:8181/job/MobHunting/683/

**Comment by Rocologo** [comment]
PLease confirm, when you have tried the snapshot
