### ISSUE TITLE
Error in console upon world startup.

### ISSUE THREAD

**Issue by KnifeKat** [Rocologo/MobHunting#419]
[03:39:19 ERROR]: Error occurred while enabling MobHunting v6.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/IncompleteRegionException
        at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:289) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.IncompleteRegionException
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar:git-Spigot-417cfb3-eb36029]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 12 more

Seems to be something with WorldEdit. I am unsure, but it shows its a MobHunting Error as well, so just making sure. Thanks in advance.

**Comment by Rocologo** [comment]
Did you solve your issue?

**Comment by KnifeKat** [comment]
As far as I am aware, WE is not currently up to date(or) I do not have access to its most recent builds from worldedit's bukkit page.

**Comment by Rocologo** [comment]
WG/WE 6.x is for MC 1.12.2 

Both WG and WE is under update, and many plugins has started to migrate to WG+WE7.0 

V7.0 is still not stable and there is still bugs, but it is better than nothing... You can find the here - notice that there is two branches. master and string-ids

http://builds.enginehub.org/job/worldedit?branch=master
http://builds.enginehub.org/job/worldedit?branch=string-ids

http://builds.enginehub.org/job/worldguard?branch=master
http://builds.enginehub.org/job/worldguard?branch=string-ids

MobHunting is using the API in the newest WG/WE builds. And both detecting mob-damage=deny and Mobhunting=allow/deny seems to work well with 7.0

I use WE 7.0.0 on my production and on my test-server, but I have to warn you, //copy&//paste does not always work yet. So you will have to update fast until its become stable.
