### ISSUE TITLE
worldedit isn't a soft-depend for this plugin 

### ISSUE THREAD

**Issue by iCrazykillerGR** [Rocologo/MobHunting#422]
so when i first run mobhunting on my server i got this:
[Server thread/ERROR]: Error occurred while enabling MobHunting v6.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/IncompleteRegionException
	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:289) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.IncompleteRegionException
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar:git-Spigot-2b0e71c-4a24108]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	... 12 more
so i went and downloaded worldedit 7.0.0 snapshot and the error was gone and mobhunting load up properly. so worldedit is not a soft-depend plugin for mobhunting. i report it as an issue cause of this.
sorry for my english btw.

**Comment by iCrazykillerGR** [comment]
forgot to mention i cant find worldedit integration on config so i can disable it. as other plugins like mcmmo, worldguard, mobstacks etc.

**Comment by Rocologo** [comment]
Fixed, and possibility to disable integration added. Please test build 694 and let me know
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by iCrazykillerGR** [comment]
launching console without worldedit and no errors. (even without changing the config enable_integration_worldedit: true to enable_integration_worldedit: false)
tested on these mobs : zombie, skeleton, witch, shulker, cow, chicken, pig ,enderman ,squid ,some fishes, horses. 
multipliers on ranks works fine.
headdrops works fine.
miultipliers in general works fine. i would like to see sneaky only on mobs attacking players tho, cause it multiplies the passive ones like cow,pig,chicken etc.
commands execution when mob killed works fine.
config reload executing command mobhunt reload worked and canges where visible. it works fine.

**Comment by iCrazykillerGR** [comment]
that was not supposed to be happening? cause sneaky i got it (its like a cheat always doubles the money), it's meant to multiply mobs that can attack back, but the other multipliers idk if they are supposed to work on passive mobs by default. if you want you can make a feature that restricts multipliers from mobs but the player decides witch mobs is going to be multiplied or not through the config. but don't restrict mobs from rank multipliers cause its given through permission so (practically) its already restricted.

sorry my english are terrible.

**Comment by iCrazykillerGR** [comment]
Not through permissions but through restriction like a feature to enable  or disable multiplier for each mob. Or a general setting to enable or disable multipliers for passive mobs.
