### ISSUE TITLE
NPEs

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#441]
Spigot 1.13.1
MH MobHunting v6.0.4-b702

Spamming NPE every 10 ticks
```
[08:38:47] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to MobHunting v6.0.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.World.a(World.java:538) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.World.a(World.java:508) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.d(BlockDiodeAbstract.java:172) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.onPlace(BlockDiodeAbstract.java:154) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.IBlockData.onPlace(SourceFile:253) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:525) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:318) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.a(BlockDiodeAbstract.java:46) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.IBlockData.a(SourceFile:261) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:677) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:77) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:659) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:301) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.npc.MasterMobHunterSign.onBlockPhysicsEvent(MasterMobHunterSign.java:562) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar-2018-09-01-0815:git-Spigot-2440e18-60d7982]
        ... 21 more
```

**Comment by Rocologo** [comment]
Not on my servers???? is there no lines after the "last line" Caused by?

**Comment by SlimeDog** [comment]
Updated ^

**Comment by Rocologo** [comment]
It look like if something has happenden to a mastermobhunter sign, maybe it has been destroyed somehow without mobhunting knows this. I will have to study the source code

**Comment by SlimeDog** [comment]
I don't have mastermobhunter signs.

**Comment by Rocologo** [comment]
In not sure what causes your problem, but I think build 704 will fix this

https://fractal.lindegaard.one:8181/job/MobHunting/704/

Please confirm.

**Comment by SlimeDog** [comment]
Resolved. Thanks for speedy and accurate response.
