### ISSUE TITLE
EventException when I killed a spider

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#458]
Spigot 1.13.2 latest
ExtraHardMode 3.13.0-3.3.2-411
MobHunting v6.0.8

[22:19:34 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.0.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:474) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(SourceFile:61) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityArrow.b(EntityArrow.java:331) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityArrow.a(EntityArrow.java:274) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityArrow.tick(EntityArrow.java:199) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityTippedArrow.tick(EntityTippedArrow.java:86) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1347) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1181) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/Vector;
        at one.lindegaard.MobHunting.compatibility.WorldGuardHelper.isAllowedByWorldGuard(WorldGuardHelper.java:96) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:807) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor377.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        ... 20 more

**Comment by Rocologo** [comment]
Which version of Worldguard and Worldedit do you use. You should use this version 

https://dev.bukkit.org/projects/worldguard/files
https://dev.bukkit.org/projects/worldedit/files

I have not tested with never development builds 
http://builds.enginehub.org/job/worldguard?branch=master
http://builds.enginehub.org/job/worldedit?branch=master

Let me know if these does not work?

**Comment by SlimeDog** [comment]
I use the bleeding-edge EngineHub builds, on test servers. So I'm just reporting that MH will get bit with those builds as they move to public release. No worries.

**Comment by SlimeDog** [comment]
Eventually that will be required. When that version is publicly released. :)

**Comment by Rocologo** [comment]
@LogGits if you use 7.0 beta 1 the plugin works

**Comment by LogGits** [comment]
Isnt beta 1 for 1.13.1 only? Im using 1.13.2

**Comment by Rocologo** [comment]
It works fine on 1.13.2 too

**Comment by LogGits** [comment]
Ok awesome il give it a go when i get home
