### ISSUE TITLE
Could not pass event EntityDeathEvent 3.0.7

### ISSUE THREAD

**Issue by nikitis** [Rocologo/MobHunting#46]
I'm running 1.9.4 Spigot.  Just updated to your 3.0.7 plugin, and get the following error.

[02:04:59] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v3.0.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:391) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.EntityLiving.die(EntityLiving.java:986) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:903) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1002) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1126) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1576) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: org/inventivetalent/bossbar/BossBarAPI$Color
        at one.lindegaard.MobHunting.compatability.BossBarAPICompat.addBar(BossBarAPICompat.java:53) ~[?:?]
        at one.lindegaard.MobHunting.MobHunting.learn(MobHunting.java:443) ~[?:?]
        at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:805) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor456.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.838_fac.jar:git-Spigot-8a048fe-a022dd2]
        ... 20 more

**Comment by Rocologo** [comment]
A quick fix on this is to disable integration to BossBarAPI in config.yml 

I will make a new release v3.0.8 today where this is fixed.

Thank you for making a ticket.

**Comment by Rocologo** [comment]
I checked my code now and can see that you actually uses BossBarAPI but I think it is an older version. Which version do you use?

I think upgrading to BossBarAPI 2.4.0 solves your problem.

**Comment by nikitis** [comment]
oh yes, i'm using an ancient version of BossBarAPI.  1.0.6.  I'll update and report back.

**Comment by nikitis** [comment]
I'm not seeing the error any more since I upgraded to BossBarApi 2.4.0.  So I think we can close this.  Thanks for the quick pointer there!  I'll do better with plugin updating.
