### ISSUE TITLE
AxeMurderer problem

### ISSUE THREAD

**Issue by WhiteKing21** [Rocologo/MobHunting#460]
Im upgrading my old server and finding this problem, I thought it was configuration or something else, then I tried at first adding BagofGold and ProtocolLib and it didn't work then I configured a totally new server instance: new World and no plugins in the newest stable spigot version from the website and the Error still appears:

`ERROR]: Error occurred while enabling MobHunting v6.0.8 (Is it up to date?)
java.lang.NoSuchFieldError: WOODEN_AXE
        at one.lindegaard.MobHunting.achievements.AxeMurderer.getSymbol(AxeMurderer.java:61) ~[?:?]
        at io.chazza.advancementapi.AdvancementManager.getAdvancementsFromAchivements(AdvancementManager.java:47) ~[?:?]
        at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:347) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

Nothing else throws an error. I just have 
Vault-1.6.7
Essentials-2.x-SNAPSHOT
EssentialsChat-2.x-SNAPSHOT
MobHunting-6.0.8

I see this in the generated config properties:
`
    axe_murderer:
      money: 1000.0
      commands: give {player} gold_ingot 1
      message: ''
`
Seems like the code it is trying to get a nonexistent Achievement. 
Am I missing something? or is this a bug?

**Comment by Rocologo** [comment]
It seems you are runing Spigot 1.12.2 

_at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348] at_

MobHunting 6.0.8 is only compatible with 1.13.x
