### ISSUE TITLE
Started getting this error in console pretty often.

### ISSUE THREAD

**Issue by kelso6969** [Rocologo/MobHunting#469]
[19:09:19 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.5.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:568) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.EntityCreeper.die(EntityCreeper.java:137) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(SourceFile:61) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1044) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1336) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1860) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at one.lindegaard.BagOfGold.Economy_BagOfGold.format(Economy_BagOfGold.java:87) ~[?:?]
        at one.lindegaard.MobHunting.rewards.RewardManager.format(RewardManager.java:213) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1095) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        ... 22 more

**Comment by Rocologo** [comment]
How does your economy format look like?

Do you use BagOfGold ? Or only MibHunting?

**Comment by kelso6969** [comment]
Use bagofgold for economy = true and also use mobhunting.

**Comment by Rocologo** [comment]
Which format has you chosen?

**Comment by kelso6969** [comment]
Sorry, not sure I understand?

**Comment by kelso6969** [comment]
in BOG:
  # Here you can change the way the numbers is formatted when you use BagOfGold as an EconomyPlugin.
  number-format: '#.#####'

I didn't change anything other than rewards really for mobhunting, did a search on format and didnt find a similar string.

**Comment by Rocologo** [comment]
Ok
