### ISSUE TITLE
Error whil starting my server 1.13.2 spigot

### ISSUE THREAD

**Issue by IKEMASTER** [Rocologo/MobHunting#470]
[Craft Scheduler Thread - 2/WARN]: [MobHunting] Failed to get resource info from spiget.org
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[spigot.jar:git-Spigot-2474d93-e693496]
	at org.inventivetalent.update.spiget.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:92) [MobHunting-6.5.0.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-2474d93-e693496]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by IKEMASTER** [comment]
problem is solved. Problem is created by WhatchCat
