### ISSUE TITLE
plugin disabled

### ISSUE THREAD

**Issue by SpartanPride7** [Rocologo/MobHunting#478]
I'm getting this error...it's probably something easy to fix but I don't know what is wrong. Not sure why its saying plugin is disabled?:

org.bukkit.command.CommandException: Cannot execute command 'mh' in plugin MobHunting v5.7.3-SNAPSHOT-B685 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1337]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1337]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Rocologo** [comment]
Post your server.log using pastebin.com so i can help with the troubleshooting

**Comment by SpartanPride7** [comment]
where would i find that? :P do you want the startup log from a restart you mean?

**Comment by Rocologo** [comment]
Yes. I need to see why MobHunting us disabled.

**Comment by SpartanPride7** [comment]
https://pastebin.com/RBaFjNnj

**Comment by yannicklamprecht** [comment]
https://gist.github.com/yannicklamprecht/2d3dd63ef845e82a95f178085a2c644f
extracted error.

**Comment by SpartanPride7** [comment]
thanks, so why is this happening though?

**Comment by Rocologo** [comment]
It looks like your blacklist file is broken. Try to rename the file and restart your server
