### ISSUE TITLE
ERROR: Could not pass event CreatureSpawnEvent to MobHunting v6.5.1

### ISSUE THREAD

**Issue by DinoTK** [Rocologo/MobHunting#479]
***Hello!*** 

My server is using **MobHunt v6.5.1** in the last week **very well**. But today, it comes with this error spamming my console right when I log in in the server. 

The spigot is **1.13.2** and I'm using: **CMI, CombatLogX, FAWE, MobArena, WorldGuard, UltraPermissions, DeluxeChat, CrazyCrates, AuthMe, AdvancedAchivements.**

```
Could not pass event CreatureSpawnEvent to MobHunting v6.5.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:446) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:383) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.World.addEntity(World.java:907) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:917) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.SpawnerCreature.a(SpawnerCreature.java:182) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:260) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NumberFormatException: For input string: "-0,50"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_201]
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Double.valueOf(Unknown Source) ~[?:1.8.0_201]
        at one.lindegaard.MobHunting.rewards.RewardManager.getPrice(RewardManager.java:947) ~[?:?]
        at one.lindegaard.MobHunting.rewards.RewardManager.getBaseKillPrize(RewardManager.java:884) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.bonusMobSpawn(MobHuntingManager.java:2006) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-2ced023]
        ... 14 more
```

**Comment by Rocologo** [comment]
You have written a wrong formatted number in the config.yml domewhere

Caused by: java.lang.NumberFormatException: For input string: "-0,50"

**Comment by Rocologo** [comment]
Next release will write a warning to the server log, and set the number to 0;

**Comment by Rocologo** [comment]
Next release will write a warning to the server log, and set the number to 0;
