### ISSUE TITLE
Compatibility error with mcmmo

### ISSUE THREAD

**Issue by thammachet** [Rocologo/MobHunting#487]
There are seen to have some error with it. Here is an error log.
[19:52:01] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.5.3
java.lang.NullPointerException: null
	at one.lindegaard.MobHunting.compatibility.McMMOCompat.getSKillTypeName(McMMOCompat.java:100) ~[?:?]
	at one.lindegaard.MobHunting.compatibility.McMMOCompatHelper.getSkilltypeName(McMMOCompatHelper.java:14) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1711) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-588]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:607) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1082) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1446) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2010) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-588]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-588]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:52:08] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.5.3
java.lang.NullPointerException: null
	at one.lindegaard.MobHunting.compatibility.McMMOCompat.getSKillTypeName(McMMOCompat.java:100) ~[?:?]
	at one.lindegaard.MobHunting.compatibility.McMMOCompatHelper.getSkilltypeName(McMMOCompatHelper.java:14) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1711) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-588]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:607) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.c(EntityLiving.java:1375) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.Block.fallOn(Block.java:581) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1112) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:208) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:833) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:2028) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2365) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:523) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityAgeable.movementTick(EntityAgeable.java:146) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityAnimal.movementTick(EntityAnimal.java:27) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2135) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1569) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1536) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1343) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1100) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-588]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Rocologo** [comment]
Which version of mcmmo are you using?

**Comment by Rocologo** [comment]
Problem found (I hope). I will make a new release today.

**Comment by thammachet** [comment]
Lastest. Thank you.=>

**Comment by thammachet** [comment]
Addition information, It seen to happen when plugin Mypet is using.

**Comment by Rocologo** [comment]
Please test Version 6.5.6 and let me know if you get any errors. Please post the errors again, if you get any?

**Comment by Rocologo** [comment]
no answer
