### ISSUE TITLE
NPE on start-up

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#488]
Spigot 1.13.2 final
MobHunting v6.5.4-SNAPSHOT-B773

```
[08:34:09] [Server thread/INFO]: [MobHunting] Enabling MobHunting v6.5.4-SNAPSHOT-B773
[08:34:09] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mYour config version is 1^[[m
[08:34:09] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mExisting config.yml loaded.^[[m
[08:34:09] [Server thread/INFO]: ^[[0;33;22m[MobHunting]^[[m Config.yml was backed up to plugins/MobHunting/backup/config.yml.bak6^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with Essentials (2.16.1.153)^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mDatabase version 7 detected.^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with WorldEdit (7.0.0-SNAPSHOT;4200-b7ea46d)^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with WorldGuard (7.0.0-SNAPSHOT;1851-36eba9c)^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with Holographic Displays (2.3.3-SNAPSHOT).^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with ProtocolLib (4.4.0).^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting]^[[m Compatibility with ActionAnnouncer is disabled in config.yml^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with PlaceholderAPI (2.9.2-DEV-59).^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with Citizens2 (2.0.25-SNAPSHOT (build 1667))^[[m
[08:34:25] [Server thread/INFO]: ^[[0;33;22m[MobHunting] ^[[mEnabling compatibility with ExtraHardMode (3.13.2-a92e6af).^[[m
[08:34:25] [Server thread/ERROR]: Error occurred while enabling MobHunting v6.5.4-SNAPSHOT-B773 (Is it up to date?)
java.lang.NullPointerException: null
        at one.lindegaard.Core.mobs.MinecraftMob.getFriendlyName(MinecraftMob.java:436) ~[?:?]
        at one.lindegaard.Core.mobs.MinecraftMob.getMinecraftMobType(MinecraftMob.java:572) ~[?:?]
        at one.lindegaard.MobHunting.mobs.ExtendedMob.getProgressAchievementLevel1(ExtendedMob.java:137) ~[?:?]
        at one.lindegaard.MobHunting.achievements.SecondHuntAchievement.getNextLevel(SecondHuntAchievement.java:45) ~[?:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager.registerAchievement(AchievementManager.java:96) ~[?:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager.registerAchievements(AchievementManager.java:131) ~[?:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager.<init>(AchievementManager.java:68) ~[?:?]
        at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:313) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Rocologo** [comment]
The dev builds are not stable yet. Im working on a 1.14 release but its not ready yet. Rollback :-)

**Comment by SlimeDog** [comment]
OK. Thanks. No worries.
