### ISSUE TITLE
Issue with Magic plugin

### ISSUE THREAD

**Issue by Dark-ash11** [Rocologo/MobHunting#489]
Hello, I get this error every time I kill a monster using wands from Magic plugin.

[02:33:48 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:573) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.EntityZombie.die(EntityZombie.java:542) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(SourceFile:61) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.EntityZombie.damageEntity(EntityZombie.java:252) ~[server.jar:git-Spigot-f09662d-f40143e]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at com.elmakers.mine.bukkit.utility.CompatibilityUtils.magicDamage(CompatibilityUtils.java:589) ~[?:?]
        at com.elmakers.mine.bukkit.action.builtin.DamageAction.perform(DamageAction.java:145) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:225) ~[?:?]
        at com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:105) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:225) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.start(ActionHandler.java:166) ~[?:?]
        at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:140) ~[?:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1465) ~[?:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1330) ~[?:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1098) ~[?:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1340) ~[?:?]
        at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:4131) ~[?:?]
        at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:4091) ~[?:?]
        at com.elmakers.mine.bukkit.wand.Wand.performAction(Wand.java:5505) ~[?:?]
        at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerAnimate(PlayerController.java:426) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[server.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1662) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PacketPlayInArmAnimation.a(SourceFile:32) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PacketPlayInArmAnimation.a(SourceFile:9) ~[server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-f09662d-f40143e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-f09662d-f40143e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.compatibility.McMMOCompat.getSKillTypeName(McMMOCompat.java:100) ~[?:?]
        at one.lindegaard.MobHunting.compatibility.McMMOCompatHelper.getSkilltypeName(McMMOCompatHelper.java:14) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1711) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server.jar:git-Spigot-f09662d-f40143e]
        ... 50 more

**Comment by Rocologo** [comment]
Im am working on the 1.14 upgrade. It will take some time before i can fix this issue. It seems to be a problem with integration to mcmmo, so please disable integration in config.yml until i can solve this issue

**Comment by Dark-ash11** [comment]
thank you and your plugin is amazing I will close this issue then
