### ISSUE TITLE
EntityPickupItemEvent Error

### ISSUE THREAD

**Issue by Dark-ash11** [Rocologo/MobHunting#494]
hello sorry to bother but I get this weird error in 1.14 Minecraft version.

[Server thread/ERROR]: Could not pass event EntityPickupItemEvent to MobHunting v6.5.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-1eece4f-0036d1b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-1eece4f-0036d1b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [server.jar:git-Spigot-1eece4f-0036d1b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.EntityItem.pickup(EntityItem.java:332) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.EntityHuman.c(EntityHuman.java:455) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.EntityHuman.movementTick(EntityHuman.java:428) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2286) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:147) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:397) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:140) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:234) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [server.jar:git-Spigot-1eece4f-0036d1b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [server.jar:git-Spigot-1eece4f-0036d1b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at com.comphenix.packetwrapper.AbstractPacket.sendPacket(AbstractPacket.java:68) ~[?:?]
        at one.lindegaard.MobHunting.compatibility.ProtocolLibHelper.pickupMoney(ProtocolLibHelper.java:92) ~[?:?]
        at one.lindegaard.MobHunting.rewards.PickupRewards.rewardPlayer(PickupRewards.java:41) ~[?:?]
        at one.lindegaard.MobHunting.rewards.EntityPickupItemEventListener.onEntityPickupItemEvent(EntityPickupItemEventListener.java:43) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor394.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-1eece4f-0036d1b]

**Comment by Rocologo** [comment]
It looks like problem with protocollib. Have you updated protocollib, which version are you using?

**Comment by Dark-ash11** [comment]
I used 4.4.0 version after you said I updated it to 4.5.0 and I didn't get the error and its fixed.

**Comment by Rocologo** [comment]
Perfect :-) Im using 4.5.0 in my test too... I close this ticket now.
