### ISSUE TITLE
Error occurred while enabling MobHunting v6.5.6 (Is it up to date?)

### ISSUE THREAD

**Issue by LegendsOfMedieval** [Rocologo/MobHunting#498]
[05:01:24 INFO]: [MobHunting] Enabling MobHunting v6.5.6
[05:01:25 INFO]: [MobHunting] Your config version is 1
[05:01:25 INFO]: [MobHunting] Existing config.yml loaded.
[05:01:25 ERROR]: Error occurred while enabling MobHunting v6.5.6 (Is it up to date?)
java.lang.NullPointerException: null
at one.lindegaard.MobHunting.WorldGroupManager.load(WorldGroupManager.java:204) ~[?:?]
at one.lindegaard.MobHunting.WorldGroupManager.<init>(WorldGroupManager.java:36) ~[?:?]
at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:178) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-625]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-625]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-625]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-625]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-625]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-625]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-625]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-625]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[05:01:25 INFO]: [MobHunting] Disabling MobHunting v6.5.6

**Comment by Rocologo** [comment]
Please show me your worldGroup.yml file

**Comment by LegendsOfMedieval** [comment]
solved
