### ISSUE TITLE
MobHunting Bug: Now Fails to connect to DB at all which in turn prevents the plugin from loading

### ISSUE THREAD

**Issue by c0mput3** [Rocologo/MobHunting#5]
Upgraded to 2.8.4 now the plugin wont load if you configure it to use a mysql.

MySql details are correct and Database does exists   

[19:05:48] [Server thread/WARN]: au.com.mineauz.MobHunting.storage.DataStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[19:05:48] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:128)
[19:05:48] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.MobHunting.onEnable(MobHunting.java:208)
[19:05:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[19:05:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:05:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:05:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[19:05:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[19:05:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[19:05:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[19:05:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[19:05:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[19:05:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[19:05:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:05:48] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[19:05:48] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:05:48] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:05:48] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:05:48] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2164)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
[19:05:48] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor135.newInstance(Unknown Source)
[19:05:48] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:05:48] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
[19:05:48] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[19:05:48] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
[19:05:48] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.MySQLDataStore.setupConnection(MySQLDataStore.java:34)
[19:05:48] [Server thread/WARN]: 	at au.com.mineauz.MobHunting.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:112)
[19:05:48] [Server thread/WARN]: 	... 12 more
[19:05:48] [Server thread/WARN]: Caused by: java.sql.SQLException: Access denied for user 'mcadmin'@'localhost' (using password: YES)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1686)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1207)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2254)
[19:05:48] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
[19:05:48] [Server thread/WARN]: 	... 25 more
[19:05:48] [Server thread/ERROR]: Error occurred while enabling MobHunting v2.8.1 (Is it up to date?)
java.lang.NullPointerException
	at au.com.mineauz.MobHunting.storage.DatabaseDataStore.closePreparedStatements(DatabaseDataStore.java:138) ~[?:?]
	at au.com.mineauz.MobHunting.storage.DatabaseDataStore.shutdown(DatabaseDataStore.java:164) ~[?:?]
	at au.com.mineauz.MobHunting.MobHunting.onEnable(MobHunting.java:213) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.2.jar:git-Spigot-5a40365-a28f87a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]

**Comment by Rocologo** [comment]
It looks like you have not ugraded to newest version or maybe the old version has not been deleted? 

_ Error occurred while enabling MobHunting v2.8.1 (Is it up to date?)
java.lang.NullPointerException_

**Comment by Rocologo** [comment]
Okay I didnt here from you, I close the ticket now.
