### ISSUE TITLE
Task #90 for MobHunting v3.1.0 exception java.lang.NullPointerException BountyManager.addBounty

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#50]
[19:39:12 WARN]: [MobHunting] Task #90 for MobHunting v3.1.0 generated an exception
java.lang.NullPointerException
at one.lindegaard.MobHunting.bounty.BountyManager.addBounty(BountyManager.java:90) ~[?:?]
at one.lindegaard.MobHunting.bounty.BountyManager.createRandomBounty(BountyManager.java:508) ~[?:?]
at one.lindegaard.MobHunting.bounty.BountyManager$1.run(BountyManager.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-71e5248]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-8a048fe-71e5248]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-8a048fe-71e5248]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-8a048fe-71e5248]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-8a048fe-71e5248]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-71e5248]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by Rocologo** [comment]
Fixed in 3.1.1. I hope, its hard to test when I only have my own and my sons account too test with.
