### ISSUE TITLE
latest version gives startup error null

### ISSUE THREAD

**Issue by mrfloris** [Rocologo/MobHunting#500]
```
[07:09:37 INFO]: [MobHunting] Enabling MobHunting v6.5.6
[07:09:37 INFO]: [MobHunting] Your config version is 1
[07:09:37 INFO]: [MobHunting] Existing config.yml loaded.
[07:09:37 INFO]: [MobHunting] Config.yml was backed up to plugins/MobHunting/backup/config.yml.bak794
[07:09:38 ERROR]: Error occurred while enabling MobHunting v6.5.6 (Is it up to date?)
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.WorldGroupManager.load(WorldGroupManager.java:204) ~[?:?]
        at one.lindegaard.MobHunting.WorldGroupManager.<init>(WorldGroupManager.java:36) ~[?:?]
        at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

```
>about
[07:11:08 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[07:11:08 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>about MobHunting
[07:11:11 INFO]: MobHunting version 6.5.6
[07:11:11 INFO]: MobHunting adds a new level of fun to hunting monsters. Now you can get money from kills, get bonuses for skilled and creative kills, and get special achievements.
[07:11:11 INFO]: Author: Rocologo
>
```

**Comment by Rocologo** [comment]
It does not on my test-server :-)

My guess is that you have an error in your worldgroups.yml file. 

Check if you have a world in the worldgroups.yml file, which has been deleted? 

If not, please post the file, so I can check if I can see an error...

**Comment by mrfloris** [comment]
Apologies for the delay in response. Offline has been a bit more hectic, my mother needs a bit more extra care lately.

The worldGroups.yml file hasn't changed in ages by the way and does indeed mention worlds that we do not use.

```
# ----------------------------------------------------------
# WorldGroups. New world are added in the Default Group
# ----------------------------------------------------------
# These worldgroups arer only use for Player Bounties. An
# bounty created in one worldgroup can not be claimed in
# another worldgroup. This is to make sure that economies
# are not mixed.
WorldGroups:
  WorldGroups:
    DefaultGroup:
    - world
    - world_nether
    - world_the_end
    CreativeGroup:
    - creative
    SurvivalGroup:
    - survival
```

We do not have any of these worlds, they're called differently. 

Restarting the server since the ticket report a couple of times, and haven't had the error anymore. It really was a one-off.

**Comment by Rocologo** [comment]
Hmm... i Think i Will close the ticket then, although the file looks wrong.
