### ISSUE TITLE
 Could not pass event PlayerMoveEvent to MobHunting v6.6.0

### ISSUE THREAD

**Issue by NTDLX** [Rocologo/MobHunting#507]
[02:47:30 ERROR]: Could not pass event PlayerMoveEvent to MobHunting v6.6.0
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
at com.comphenix.packetwrapper.AbstractPacket.sendPacket(AbstractPacket.java:68) ~[?:?]
at one.lindegaard.MobHunting.compatibility.ProtocolLibHelper.pickupMoney(ProtocolLibHelper.java:92) ~[?:?]
at one.lindegaard.MobHunting.rewards.RewardListeners.onPlayerMoveOverRewardEvent(RewardListeners.java:247) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor241.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-23]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-23]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-23]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1101) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:972) ~[patched_1.14.1.jar:git-Paper-23]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.1.jar:git-Paper-23]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by Rocologo** [comment]
Have you upgraded ProtocolLib?

**Comment by NTDLX** [comment]
Thank you, the problem has been solved
