### ISSUE TITLE
MySql Error

### ISSUE THREAD

**Issue by NTDLX** [Rocologo/MobHunting#509]
[14:23:52] [Server thread/INFO]: [MobHunting] Enabling MobHunting v6.6.0
[14:23:52] [Server thread/INFO]: [MobHunting] Your config version is 1
[14:23:52] [Server thread/INFO]: [MobHunting] Existing config.yml loaded.
[14:23:52] [Server thread/INFO]: [MobHunting] Config.yml was backed up to plugins\MobHunting\backup\config.yml.bak9
[14:23:52] [Server thread/INFO]: [MobHunting] Enabling compatibility with Essentials (2.16.1.156)
[14:23:52] [Server thread/WARN]: one.lindegaard.MobHunting.storage.DataStoreException: Error creating sql connection
[14:23:52] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.MySQLDataStore.setupConnection(MySQLDataStore.java:66)
[14:23:52] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:175)
[14:23:52] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:201)
[14:23:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:23:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[14:23:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[14:23:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[14:23:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[14:23:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[14:23:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[14:23:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843)
[14:23:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:23:52] [Server thread/WARN]: Caused by: java.sql.SQLException: The connection property 'useSSL' only accepts values of the form: 'true', 'false', 'yes' or 'no'. The value 'false?autoReconnect=true' is not in this set.
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionPropertiesImpl$ConnectionProperty.validateStringValues(ConnectionPropertiesImpl.java:314)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionPropertiesImpl$BooleanConnectionProperty.initializeFrom(ConnectionPropertiesImpl.java:91)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionPropertiesImpl$ConnectionProperty.initializeFrom(ConnectionPropertiesImpl.java:216)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionPropertiesImpl.initializeProperties(ConnectionPropertiesImpl.java:2538)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.initializeDriverProperties(ConnectionImpl.java:3143)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:762)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[14:23:52] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:23:52] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:23:52] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:23:52] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
[14:23:52] [Server thread/WARN]: 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107)
[14:23:52] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.MySQLDataStore.setupConnection(MySQLDataStore.java:56)
[14:23:52] [Server thread/WARN]: 	... 11 more
[14:23:52] [Server thread/ERROR]: Error occurred while enabling MobHunting v6.6.0 (Is it up to date?)
java.lang.NullPointerException: null
	at one.lindegaard.MobHunting.storage.DatabaseDataStore.shutdown(DatabaseDataStore.java:354) ~[?:?]
	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:205) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.1.jar:git-Paper-26]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.1.jar:git-Paper-26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.1.jar:git-Paper-26]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-26]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-26]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.1.jar:git-Paper-26]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[14:23:52] [Server thread/INFO]: [MobHunting] Disabling MobHunting v6.6.0
[14:23:52] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.16.1.156
[14:23:52] [Server thread/INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild v2.16.1.156

**Comment by Rocologo** [comment]
Show me the database section from the config.yml

**Comment by NTDLX** [comment]
database:

  # Type of database to use. Valid values are: sqlite, mysql
  type: mysql
  database_name: j**a?useSSL=false
  mysql:
    username: j**a
    password: K*****A
    host: localhost:3306

  # This is the database layout version. Mostly for internal use and you should not need
  # to chance this value. In case you decide to delete your database and let it recreate
  # or if you chance database type sqlite/mysql you should set this value to 0 again.
  database_version: 0

**Comment by Rocologo** [comment]
Hou cant White

database_name: ja?useSSL=false

Remote The parameter
