### ISSUE TITLE
Console flooded with warnings and exceptions related to bungee (looks like) on craftbukkit 1.9 R1

### ISSUE THREAD

**Issue by tacogerbil** [Rocologo/MobHunting#52]
10:59:49 INFO]: [MobHunting] Enabling MobHunting v3.1.5
[10:59:49 INFO]: [MobHunting] Missing key in language file: mobhunting.grinding.detected
[10:59:49 INFO]: [MobHunting] Updated en_US.lang translation
[10:59:49 INFO]: [MobHunting] Missing key in language file: mobhunting.grinding.detected
[10:59:49 INFO]: [MobHunting] Updated zh_CN.lang translation
[10:59:49 INFO]: [MobHunting] Enabling compatability with Essentials (TeamCity)
[10:59:49 INFO]: [MobHunting] Enabling compatability with WorldEdit (6.1.1-SNAPSHOT;3501-c85c9f7)
[10:59:49 INFO]: [MobHunting] Enabling compatability with WorldGuard (6.1.2-SNAPSHOT;1653-65e48d1 with custom flags plugin.)
[10:59:49 INFO]: [MobHunting] Enabling compatability with Citizens (2.0.17-SNAPSHOT (build 1362))
[10:59:50 INFO]: [MobHunting] Enabling compatability with MobArena (0.97.1)
[10:59:50 INFO]: [MobHunting] Enabling compatability with LibsDisguises (9.0.6)
[10:59:50 INFO]: [MobHunting] Enabling compatability with BattleArena (3.9.10.8)
[10:59:50 INFO]: [MobHunting] Checking for new updates...
[10:59:50 WARN]: Exception in thread "pool-3-thread-96"
[10:59:50 WARN]: org.apache.commons.lang.UnhandledException: Plugin MobHunting v3.1.5 generated an exception while executing task 31325
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at one.lindegaard.MobHunting.MetricsManager$17.getValue(MetricsManager.java:188)
        at org.mcstats.Metrics.postPlugin(Metrics.java:397)
        at org.mcstats.Metrics.access$400(Metrics.java:61)
        at org.mcstats.Metrics$1.run(Metrics.java:227)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more

[10:59:52 INFO]: [MobHunting] No update found.

**Comment by Rocologo** [comment]
I havnt tested CraftBukkit 1.9 for some time now, but I will do so tomorrow.

**Comment by Rocologo** [comment]
I always test against SpigotMC 1.9.4 and only randomly on the other versions.

**Comment by Rocologo** [comment]
Fixed in v 3.1.6

**Comment by tacogerbil** [comment]
Thank you Rocologo :)  
Hope you have a wonderful day :)
