### ISSUE TITLE
And with the latest update i get this after I run it an hour or so

### ISSUE THREAD

**Issue by MrKiller01** [Rocologo/MobHunting#522]
[21:31:05 ERROR]: Could not pass event EntityDamageByEntityEvent to MobHunting v
6.6.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:507) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:492) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(Cra
ftEventFactory.java:102) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDam
ageEvent(CraftEventFactory.java:762) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fd
bc]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityD
amageEvent(CraftEventFactory.java:661) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46
fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingE
ntityDamageEvent(CraftEventFactory.java:794) [spigot-1.13.2.jar:git-Spigot-1a350
4a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving
.java:1445) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.j
ava:879) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.
java:967) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.ja
va:792) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.
java:625) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.damageEntity(Enti
tyHumanNPC.java:151) [Citizens-2.0.25-b1702.jar:?]
        at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.jav
a:1221) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityPhantom$i.e(EntityPhantom.java:28
5) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(SourceFil
e:129) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentien
t.java:659) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.
java:2254) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityIns
entient.java:510) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityPhantom.movementTick(EntityPhanto
m.java:110) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:209
8) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.
java:248) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.EntityPhantom.tick(EntityPhantom.java:8
1) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331
) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1298) [spigot-1.13.2
.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132) [sp
igot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.ja
va:583) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
968) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
831) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchFieldError: hSpawnedHorses
        at one.lindegaard.MobHunting.compatibility.McMMOHorses.isMcMMOHorse(McMM
OHorses.java:60) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDamage(MobHuntingMan
ager.java:491) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor454.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-a46fdbc]
        ... 32 more
[21:31:15 INFO]: Unhandled moon phase.
>

**Comment by MrKiller01** [comment]
An infernal phantom attacked an NPC....... that has npc_police and npc_destinations on it with sentinel

**Comment by Rocologo** [comment]
Make sure that you have updated Mcmmohorses

hSpawnedHorses
at one.lindegaard.MobHunting.compatibility.McMMOHorses.isMcMMOHorse(McMM
OHorses.java:60) ~[?:?]
at

**Comment by MrKiller01** [comment]
version 4.3.55, and this is the latest.....

**Comment by MrKiller01** [comment]
Don't worry about it too much, it still works and we (I for sure) know that you will take care of your plugin.

**Comment by Rocologo** [comment]
It seems that one of the newest versions of McMMOHorses broke the compatibility. I have updated to McMMOHorses V4.3.55 in next release. You will need to upgrade to this version or newer.
