### ISSUE TITLE
Could not pass event PlayerInteractEvent to MobHunting v6.7.2

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#527]
Spamming my console to utter high hell!
paper 1.12.2 using 6.7.2

https://gist.github.com/FrozenBeard/0cc9f069382b2a5eb5ddb2c3d7d177cd

**Comment by Darcion** [comment]
i got this bug too with 6.7.2 and spigot 1.14.3

[18:03:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MobHunting v6.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:396) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1189) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot.jar:git-Spigot-595711b-e8b39d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
	at one.lindegaard.MobHunting.leaderboard.WorldLeaderboard.isSpaceAvailable(WorldLeaderboard.java:142) ~[?:?]
	at one.lindegaard.MobHunting.leaderboard.LeaderboardManager.createLeaderboard(LeaderboardManager.java:124) ~[?:?]
	at one.lindegaard.MobHunting.commands.LeaderboardCommand.onClickSign(LeaderboardCommand.java:349) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-595711b-e8b39d4]
	... 20 more

**Comment by Rocologo** [comment]
Please test this build and let me know if this solves the problem.

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Darcion** [comment]
> 
> 
> Please test this build and let me know if this solves the problem.
> 
> https://fractal.lindegaard.one:8181/job/MobHunting/831/

this fixed it for me.

**Comment by stw222** [comment]
it fixed this specific error for me but i opened a seperate issue for a different error im having

**Comment by Rocologo** [comment]
Released I 6.7.3
