### ISSUE TITLE
Could not pass event MobHuntKillEvent to MobHunting v6.7.2

### ISSUE THREAD

**Issue by RealCorebb** [Rocologo/MobHunting#529]
![QQ截图20190703132133](https://user-images.githubusercontent.com/33654314/60565315-b1315900-9d95-11e9-8241-96ed1d14fc5a.png)
`Could not pass event MobHuntKillEvent to MobHunting v6.7.2
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.achievements.AchievementManager.awardAchievement(AchievementManager.java:404) ~[?:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager.awardAchievementProgress(AchievementManager.java:533) ~[?:?]
        at one.lindegaard.MobHunting.achievements.EighthHuntAchievement.onKillCompleted(EighthHuntAchievement.java:92) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor839.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-122]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-122]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1498) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.3.jar:git-Paper-122]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1416) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(EntityMonster.java:56) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityZombie.damageEntity(EntityZombie.java:280) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityPigZombie.damageEntity(EntityPigZombie.java:138) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityArrow.a(EntityArrow.java:375) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityArrow.a(EntityArrow.java:287) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityArrow.tick(EntityArrow.java:198) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.EntityTippedArrow.tick(EntityTippedArrow.java:87) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.World.a(World.java:933) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-122]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

**Comment by RealCorebb** [comment]
Running on Papermc 1.14.3.
I have installed mcmmo、Essentials、Citizens2  .All of thems are lateset version

**Comment by Rocologo** [comment]
Please try to disable achievments in config.yml 

And let me know if this works?

**Comment by RealCorebb** [comment]
> And let me know if this works?

Yes.It works.

**Comment by Rocologo** [comment]
Thank. Unfortunately it seems that Paper does hot have the Achievements API, so I will have to disable this automatically in next version.

Thank you for your help.
