### ISSUE TITLE
NoSuchElement Eroor in my 1.13.2 spigot Server 

### ISSUE THREAD

**Issue by Zaohon** [Rocologo/MobHunting#530]
Plugin runs perfectly when starting the server , but when player enter , it throw this exception

`[16:57:42] [Server thread/WARN]: [BagOfGold] Task #3365 for BagOfGold v2.6.8 generated an exception
java.util.NoSuchElementException: null
	at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at one.lindegaard.Core.skins.Skins_1_13_R2.getSkin(Skins_1_13_R2.java:20) ~[?:?]
	at one.lindegaard.BagOfGold.rewards.CustomItems.getPlayerHead(CustomItems.java:129) ~[?:?]
	at one.lindegaard.BagOfGold.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:122) ~[?:?]
	at one.lindegaard.BagOfGold.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:113) ~[?:?]
	at one.lindegaard.BagOfGold.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:234) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[16:57:42] [Server thread/WARN]: [MobHunting] Task #3392 for MobHunting v6.7.4 generated an exception
java.util.NoSuchElementException: null
	at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at one.lindegaard.Core.skins.Skins_1_13_R2.getSkin(Skins_1_13_R2.java:20) ~[?:?]
	at one.lindegaard.MobHunting.rewards.CustomItems.getPlayerHead(CustomItems.java:121) ~[?:?]
	at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:125) ~[?:?]
	at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:112) ~[?:?]
	at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:341) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
`
I m from china , it is a excellent plugin  ! thanks for your hard working !

**Comment by Rocologo** [comment]
Im not able reproduce this bug, but I think I have made a fix. Can you please help me with the testing. Please test this build:

https://fractal.lindegaard.one:8181/job/BagOfGold/281/

And let me know if it works?

**Comment by Zaohon** [comment]
it works perfectly ! Thanks for your reply ! You and these plugins are quite awesome ! 
And sry for my late replay

**Comment by Zaohon** [comment]
I delete the plugin folder and restart to generate a new one , then when a player enter in it shows me that`[BagOfGold][m mTranslationTable has not key: bagofgold.reward.name[m`
idk if it is a bug

**Comment by Rocologo** [comment]
Its not a bug, its just telling you that a key has been created because it was missing. You will get a similar lot of warnings, if you install a third party mob plugin like MythicMobs and smilar.
