### ISSUE TITLE
java.lang.NoClassDefFoundError: one/lindegaard/Core/skins/Skins_1_14_R1

### ISSUE THREAD

**Issue by myfbone** [Rocologo/MobHunting#537]
last build
1.14.4
[19:31:38 INFO]: G_Mixer[/37.52.157.176:29556] logged in with entity id 278 at ([world]34.829986939833994, 70.0, -4.416170525709221)
[19:31:38 WARN]: [MobHunting] Task #882 for MobHunting v6.7.9 generated an exception
java.lang.NoClassDefFoundError: one/lindegaard/Core/skins/Skins_1_14_R1
        at one.lindegaard.MobHunting.rewards.CustomItems.getSkinsClass(CustomItems.java:68) ~[?:?]
        at one.lindegaard.MobHunting.rewards.CustomItems.getPlayerHead(CustomItems.java:118) ~[?:?]
        at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:125) ~[?:?]
        at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:112) ~[?:?]
        at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:341) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-147]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-147]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-147]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-147]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-147]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-147]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Rocologo** [comment]
fixed in 6.8.0
