### ISSUE TITLE
Entity removal/death error in console

### ISSUE THREAD

**Issue by ShibeTemple** [Rocologo/MobHunting#539]
`[18:47:49 WARN]: [mcMMO] Invalid mcMMO skill ()
[18:47:49 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.8.0
com.gmail.nossr50.api.exceptions.InvalidSkillException: That is not a valid skill.
        at com.gmail.nossr50.api.ExperienceAPI.getSkillType(ExperienceAPI.java:1142) ~[?:?]
        at com.gmail.nossr50.api.ExperienceAPI.addLevel(ExperienceAPI.java:576) ~[?:?]
        at one.lindegaard.MobHunting.compatibility.McMMOCompat.addLevel(McMMOCompat.java:113) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1731) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.3.jar:git-Paper-134]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1416) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1031) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1676) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2068) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-134]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by Rocologo** [comment]
Fixed in v6.8.3
