### ISSUE TITLE
Exception while executing task 41 (1_9_R2//v3.1.5)

### ISSUE THREAD

**Issue by HairyDaddy** [Rocologo/MobHunting#54]
This pops up on server initiation, thus preventing the plugin from working: 
[17:53:13] [Craft Scheduler Thread - 7/WARN]: org.apache.commons.lang.UnhandledException: Plugin MobHunting v3.1.5 generated an exception while executing task 41
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at org.mcstats.Metrics.postPlugin(Metrics.java:357)
	at org.mcstats.Metrics.access$4(Metrics.java:350)
	at org.mcstats.Metrics$1.run(Metrics.java:245)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

The latest version (3.1.8) doesn’t work either.

**Comment by Rocologo** [comment]
This happens because you have installed en old plugin (not MobHunting) which is not updated for MInecraft 1.9+ where "org.bukkit.Server.getOnlinePlayers()" was removed. The only way you can solve this problem is to find the plugin and ask the developer of the plugin to update it. My plugin uses newest version of Metrics, but is loaded AFTER the plugin which causes this error and therefore you see this error.
