### ISSUE TITLE
1.14.4 support?

### ISSUE THREAD

**Issue by spamattack123** [Rocologo/MobHunting#544]
Money not being given on kills. Plugin loads and appears to work?

**Comment by Rocologo** [comment]
Enable debug and learn and try again

/mh debug

/mh learn

**Comment by spamattack123** [comment]
Will this enable a log file?

**Comment by Rocologo** [comment]
Have you read the commands page? It will explain.

**Comment by spamattack123** [comment]
I dont know how to fix this problem as it arrises here.

 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:708) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1365) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1322) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1169) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(SourceFile:72) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:387) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:210) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:346) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2217) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.EntityMonster.tick(SourceFile:51) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.World.a(World.java:745) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1069) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.protection.flags.Flags
        at one.lindegaard.MobHunting.compatibility.WorldGuardMobHuntingFlag.getMobDamageFlag(WorldGuardMobHuntingFlag.java:32) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:829) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]

**Comment by Rocologo** [comment]
It looks like a problem with Worldguard. Make sure worldguard is updated to newest 7.0.x version

**Comment by Rocologo** [comment]
Did you solve this problem?

**Comment by spamattack123** [comment]
Yes
