### ISSUE TITLE
Craftbukkit 1.9 (sorry!!) :)

### ISSUE THREAD

**Issue by tacogerbil** [Rocologo/MobHunting#55]
get this error with the new version..
[11:16:58 INFO]: [MobHunting] Checking for new updates...
[11:16:58 WARN]: Exception in thread "pool-3-thread-23"
[11:16:58 WARN]: org.apache.commons.lang.UnhandledException: Plugin MobHunting v3.1.8 generated an exception while executing task 209
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.MetricsManager$26.getValue(MetricsManager.java:251)
        at org.mcstats.Metrics.postPlugin(Metrics.java:397)
        at org.mcstats.Metrics.access$400(Metrics.java:61)
        at org.mcstats.Metrics$1.run(Metrics.java:227)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Rocologo** [comment]
This will be fixed in next release. (Later today).

**Comment by Rocologo** [comment]
Fixed in V3.1.9
