### ISSUE TITLE
Could not pass event BlockPhysicsEvent to MobHunting v6.8.5

### ISSUE THREAD

**Issue by sithnar** [Rocologo/MobHunting#561]
Hi, i get this error... i think its when zombies are dying from being dropped.

I run Spigot 1.12.2 

```
[14:53:40 ERROR]: Could not pass event BlockPhysicsEvent to MobHunting v6.8.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.a(World.java:568) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.applyPhysics(World.java:520) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.update(World.java:476) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.notifyAndUpdatePhysics(World.java:428) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:412) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:145) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeId(CraftBlock.java:132) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setType(CraftBlock.java:123) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setType(CraftBlock.java:118) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at one.lindegaard.MobHunting.rewards.RewardManager.removeReward(RewardManager.java:608) [MobHunting-6.8.5.jar:?]
        at one.lindegaard.MobHunting.rewards.RewardListeners.onRewardBlockBreak(RewardListeners.java:762) [MobHunting-6.8.5.jar:?]
        at sun.reflect.GeneratedMethodAccessor395.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:893) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPhysicsEvent.getSourceBlock()Lorg/bukkit/block/Block;
        at one.lindegaard.MobHunting.rewards.RewardListeners.onBlockPhysicsEvent(RewardListeners.java:745) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        ... 35 more
```

and i have these plugins loaded
```
[16:04:00 INFO]: [PlugMan] Plugins (48): AgarthaLib (2.17.1), BetterBeds (0.6.1-SNAPSHOT (build #4)), BKCommonLib (1.14.4-v1), Citizens (2.0.25-SNAPSHOT (build 1737)), ClearLag (3.0.6), CoreProtect (2.14.2), CraftBook (3.9-SNAPSHOT-jenkins-CraftBook-206), DiscordSRV (1.17.1), DreamFish (4.4.6), dtlTraders (5.0.7), EditableSign (3.2.0), EmptyWorldGenerator (1.7), Essentials (2.17.1.2), EssentialsAntiBuild (2.17.1.2), EssentialsChat (2.17.1.2), EssentialsSpawn (2.17.1.2), FastLeafDecay (1.12-compat-1.0), GriefPrevention (16.8), Holograms (2.5.0-SNAPSHOT), HologramsPlaceholders (2.1.0-SNAPSHOT), LampControl (3.0), Lift (56), Maplands (0.6), MCLink (0.3.2.15), MobHunting (6.8.5), Multiverse-Core (2.5.0-b727), Multiverse-NetherPortals (2.4-b530), Multiverse-Portals (2.5.0-b751), Orebfuscator4 (4.3.3), PacketListenerApi (3.7.3-SNAPSHOT), PermissionsEx (1.23.4), PerWorldInventory (1.11.3), PlaceholderAPI (2.10.3), PlugMan (2.1.5), ProtocolLib (4.4.0), SavageDeathChest (1.7.0-beta4), SavageDeathCompass (1.4.5), Sentinel (1.4.5 (build 155)), StableMaster (1.0.4), StaffPlus (3.2.9.3), TAB (2.5.0), Twerking-Crops (7.2), UltimateAutoRestart (2.2), Vault (1.6.6-b${env.TRAVIS_BUILD_NUMBER}), WirelessRedstone (4.0.1), WorldBorder (1.8.7), WorldEdit (6.1.8-SNAPSHOT;cd4729f), WorldGuard (6.2.1;84bc322)
```

**Comment by Rocologo** [comment]
I see it is related to the Spigo 1.12.2, I have have to test my plugin on 1.12.2 and find a solution.

**Comment by Rocologo** [comment]
The bug is fixed in this build: 
https://fractal.lindegaard.one:8181/job/MobHunting/923/

Notice that I have added a new feature called Speed Grinding and the test is still ongoing. (https://github.com/Rocologo/MobHunting/issues/555) if you are having problems with the Grinding detection. Please report on the other ticket. #555

**Comment by sithnar** [comment]
Thanks for the quick response, been testing this since you posted it, I have yet to see any errors at all on the console.

Will keep monitoring it for a few days, but it looks like you have fixed the issue.

**Comment by sithnar** [comment]
Issue still stands, same error still.

**Comment by Rocologo** [comment]
Strange I have tested this.... please show me the the error from the console again. Maybe it is the same error, but another place in the code...

**Comment by sithnar** [comment]
Most recent error.
```
[20:16:12 ERROR]: Could not pass event BlockPhysicsEvent to MobHunting v6.8.6-SNAPSHOT-B923
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.a(World.java:568) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.applyPhysics(World.java:522) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.update(World.java:476) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.notifyAndUpdatePhysics(World.java:428) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:412) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:145) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeId(CraftBlock.java:132) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setType(CraftBlock.java:123) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setType(CraftBlock.java:118) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at one.lindegaard.MobHunting.rewards.RewardManager.removeReward(RewardManager.java:609) [MobHunting-6.8.6-SNAPSHOT-B923.jar:?]
        at one.lindegaard.MobHunting.rewards.RewardListeners.onRewardBlockBreak(RewardListeners.java:774) [MobHunting-6.8.6-SNAPSHOT-B923.jar:?]
        at sun.reflect.GeneratedMethodAccessor332.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:893) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPhysicsEvent.getSourceBlock()Lorg/bukkit/block/Block;
        at one.lindegaard.MobHunting.rewards.RewardListeners.onBlockPhysicsEvent(RewardListeners.java:749) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        ... 35 more
```
