### ISSUE TITLE
Error on EntityDeathEvent

### ISSUE THREAD

**Issue by FabioZumbi12** [Rocologo/MobHunting#569]
Having this error on 6.8.9

```
[15:24:59 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.8.9
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:461) ~[?:?]
        at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:65) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:659) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-175]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1419) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(EntityMonster.java:56) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityGuardian.damageEntity(SourceFile:345) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.b(EntityLiving.java:1541) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Block.fallOn(Block.java:606) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.a(Entity.java:1082) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.a(EntityLiving.java:225) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:590) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2208) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityGuardian.e(SourceFile:365) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2559) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityGuardian.movementTick(SourceFile:299) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2321) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityMonster.tick(EntityMonster.java:37) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:431) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by Rocologo** [comment]
Is this the ful ltext? Dont you have "Caused by...." in the error ?

**Comment by Rocologo** [comment]
hmm im not sure about what triggers this error and I dont see this on my own servers, so I need your help.

I have added some debug information. Could you please test this build? 

https://fractal.lindegaard.one:8181/view/MainProject/job/MobHunting/948/

**Comment by FabioZumbi12** [comment]
Sorry fot too long response, i am bit busy :/

Here's the error log with this version:

```
[16:24:27 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.9.1
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:446) ~[?:?]
        at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:65) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:659) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-175]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1419) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityIronGolem.die(EntityIronGolem.java:160) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.burnFromLava(Entity.java:482) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:419) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:212) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2285) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:431) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
> 
```

**Comment by Rocologo** [comment]
This is fixed in newest version



Sendt fra Samsung Galaxy S10+


-------- Oprindelig besked --------
Fra: FabioZumbi12 <notifications@github.com>
Dato: 06/10/2019 21.25 (GMT+01:00)
Til: Rocologo/MobHunting <MobHunting@noreply.github.com>
Cc: Rocologo <Rocologo@hotmail.com>, State change <state_change@noreply.github.com>
Emne: Re: [Rocologo/MobHunting] Error on EntityDeathEvent (#569)


Sorry fot too long response, i am bit busy :/

Here's the error log with this version:

[16:24:27 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.9.1
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:446) ~[?:?]
        at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:65) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:659) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-175]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1419) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityIronGolem.die(EntityIronGolem.java:160) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.burnFromLava(Entity.java:482) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:419) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:212) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2285) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:431) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
