### ISSUE TITLE
Grinding detection issue

### ISSUE THREAD

**Issue by ArtNRG** [Rocologo/MobHunting#574]
MobHunting-6.9.2-SNAPSHOT-B950
Paper version git-Paper-647 (MC: 1.13.2)

mh debug log: https://pastebin.com/raw/CnNmkJBB

Players are receiving rewards in the grinding areas even if I blacklist the area manually using /mh blacklistarea

**Comment by aenaveen** [comment]
Also I am getting "Could not pass event EntityDeathEvent to MobHunting v6.9.1"
Rest of it error points to grinding related, and my players have been reporting getting money from grinding. 
at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_221]
at one.lindegaard.MobHunting.grinding.GrindingManager.isPlayerSpeedGrinding(GrindingManager.java:85) ~[?:?]
at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1323) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-207]

Rest of it : https://pastebin.com/QivJA7ZX

**Comment by Rocologo** [comment]
This is fixrd i v6.9.2



Sendt fra Samsung Galaxy S10+


-------- Oprindelig besked --------
Fra: aenaveen <notifications@github.com>
Dato: 01/10/2019 17.33 (GMT+01:00)
Til: Rocologo/MobHunting <MobHunting@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: Re: [Rocologo/MobHunting] Grinding detection issue (#574)


Also I am getting "Could not pass event EntityDeathEvent to MobHunting v6.9.1"
Rest of it error points to grinding related, and my players have been reporting getting money from grinding.
at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_221]
at one.lindegaard.MobHunting.grinding.GrindingManager.isPlayerSpeedGrinding(GrindingManager.java:85) ~[?:?]
at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1323) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-207]

Rest of it : https://pastebin.com/QivJA7ZX

**Comment by ArtNRG** [comment]
The issue still exists.
MobHunting-6.9.2

```
[01:41:37] Found a blacklisted player specific grinding Area: (world,4788,58,7283)
[01:41:37] DampenedKills reached the limit 15, no rewards paid. Grinding Spot registered.
--
[01:41:41] Grinding detected : CraftPlayer{name=Art_NRG}
--
[01:41:42] Last Kill Area Center was null. DampenedKills reset to 0
[01:41:42] Art_NRG got a reward ($5.90)
```

Log: https://pastebin.com/raw/gbtNkKCb

**Comment by Rocologo** [comment]
Strange. I thought it was same bug as ticket #571, #572 #573.... 

Thank for the debug information it helps me alot, when I am goind to solve this bug. I see clearly the problem:

This is wrong: 
GrindingManager: average kill time=0

**Comment by ArtNRG** [comment]
Is there any news? There is no grinding detection now even if I set the detect_speed_grinding to false.

**Comment by aenaveen** [comment]
https://pastebin.com/raw/wpUqsShh

14:55:06
Could not pass event EntityDeathEvent to MobHunting v6.9.6
Console

14:55:06
java.lang.NullPointerException: null
at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:448) ~[?:?]
at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:65) ~[?:?]
at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:659) ~[?:?]

Again some problem with grinding detection. This error wouldn't come before 6.9.6
please fix asap I cannot use console to do anything cus this warning is spamming for every mobkill.

**Comment by Sikatsu** [comment]
How is this going?
