### ISSUE TITLE
[SQLITE_BUSY]  The database file is locked (database is locked)

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#586]
https://timings.aikar.co/?id=ffe20f835dc24a9eaac033cbe35b369f

Why does this happen? Here's the error that shows in the console periodically, no idea what started it:

`[18:06:13] [MH TaskThread/WARN]: one.lindegaard.MobHunting.storage.DataStoreException: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[18:06:13] [MH TaskThread/WARN]: 	at one.lindegaard.MobHunting.storage.SQLiteDataStore.savePlayerStats(SQLiteDataStore.java:295)
[18:06:13] [MH TaskThread/WARN]: 	at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:47)
[18:06:13] [MH TaskThread/WARN]: 	at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:13)
[18:06:13] [MH TaskThread/WARN]: 	at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:404)
[18:06:13] [MH TaskThread/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[18:06:13] [MH TaskThread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[18:06:13] [MH TaskThread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[18:06:13] [MH TaskThread/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:918)
[18:06:13] [MH TaskThread/WARN]: 	at org.sqlite.core.DB.exec(DB.java:178)
[18:06:13] [MH TaskThread/WARN]: 	at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404)
[18:06:13] [MH TaskThread/WARN]: 	at one.lindegaard.MobHunting.storage.SQLiteDataStore.savePlayerStats(SQLiteDataStore.java:262)
[18:06:13] [MH TaskThread/WARN]: 	... 3 more`

This is the second time this has come up for me, I think restarting the server may fix it, but it seems like a bug.

Edit: restarting resolves the issue

**Comment by Rocologo** [comment]
This should be fixed in build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/
