### ISSUE TITLE
Simplepets support

### ISSUE THREAD

**Issue by DJLost12** [Rocologo/MobHunting#607]
The below errors happened while riding a simplepet pet and when I used the gui to name simplepet. Is there any chance there is something in the below errors that would make integration /support /two plugins play nice?

 [Server thread/ERROR]: Could not pass event InventoryClickEvent to MobHunting v7.0.0
java.lang.IllegalStateException: Title not set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[patched_1.15.2.jar:git-Paper-88]
        at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClickOnGoing(AchievementManager.java:978) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor835.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-88]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2328) ~[?:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-88]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[00:14:19] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MobHunting v7.0.0
java.lang.IllegalStateException: Title not set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[patched_1.15.2.jar:git-Paper-88]
        at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClickCompleted(AchievementManager.java:958) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor834.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-88]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2328) ~[?:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-88]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[00:14:19] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MobHunting v7.0.0
java.lang.IllegalStateException: Title not set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[patched_1.15.2.jar:git-Paper-88]
        at one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClickNotStarted(AchievementManager.java:997) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor833.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-88]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-88]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2328) ~[?:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-88]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-88]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Rocologo** [comment]
I hope this is fixed in next version

**Comment by Rocologo** [comment]
The problem was that you had some inventories without a name, I was not aware that this was possible.

**Comment by Rocologo** [comment]
You can test this build if you want to: https://fractal.lindegaard.one:8181/job/MobHunting/982/
