### ISSUE TITLE
Task #607866 for MobHunting v7.0.0 generated an exception  NPE

### ISSUE THREAD

**Issue by DJLost12** [Rocologo/MobHunting#617]
```
[22:58:12 WARN]: [MobHunting] Task #607866 for MobHunting v7.0.0 generated an exception
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:664) ~[?:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:603) ~[?:?]
        at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:341) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"72a4f18"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"72a4f18"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Tuinity-"72a4f18"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"72a4f18"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Tuinity-"72a4f18"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Tuinity-"72a4f18"]
```

Happens on every player join. Specific to tuinity.

**Comment by Rocologo** [comment]
i dont know this server you are using "patched_1.15.2." so I dont know if this can be fixed, but you can disable Advancements in config.yml and then the problem is solved.

**Comment by Sikatsu** [comment]
Tuinity is a fork of paper for high performance with higher player counts.

**Comment by Rocologo** [comment]
Please let me know is this is a problem on newest snapshot

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Sikatsu** [comment]
It seems to be solved :)
