### ISSUE TITLE
he money was picked up by org.bukkit.craftbukkit.v1_8_R3.block.CraftHopper@e87001c3, event was cancelled. Please show log to Developer.

### ISSUE THREAD

**Issue by HalCroves** [Rocologo/MobHunting#62]
Hi !
I repost for my problem with your last update :
`[Server thread/WARN]: [MobHunting] WARNING! The money was picked up by org.bukkit.craftbukkit.v1_8_R3.block.CraftHopper@e87001c3, event was cancelled. Please show log to Developer.`
And :
```
[17:40:20] [Server thread/WARN]: java.lang.UnsupportedOperationException
[17:40:20] [Server thread/WARN]:     at java.util.AbstractList.add(AbstractList.java:148)
[17:40:20] [Server thread/WARN]:     at java.util.AbstractList.add(AbstractList.java:108)
[17:40:20] [Server thread/WARN]:     at one.lindegaard.MobHunting.MobHuntingManager.getOnlinePlayers(MobHuntingManager.java:101)
[17:40:20] [Server thread/WARN]:     at one.lindegaard.MobHunting.achievements.AchievementManager.broadcast(AchievementManager.java:251)
[17:40:20] [Server thread/WARN]:     at one.lindegaard.MobHunting.achievements.AchievementManager.awardAchievement(AchievementManager.java:303)
[17:40:20] [Server thread/WARN]:     at one.lindegaard.MobHunting.achievements.AchievementManager.awardAchievementProgress(AchievementManager.java:379)
[17:40:20] [Server thread/WARN]:     at one.lindegaard.MobHunting.achievements.SeventhHuntAchievement.onKillCompleted(SeventhHuntAchievement.java:81)
[17:40:20] [Server thread/WARN]:     at sun.reflect.GeneratedMethodAccessor269.invoke(Unknown Source)
[17:40:20] [Server thread/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:40:20] [Server thread/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:40:20] [Server thread/WARN]:     at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:1096)
[17:40:20] [Server thread/WARN]:     at sun.reflect.GeneratedMethodAccessor230.invoke(Unknown Source)
[17:40:20] [Server thread/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:40:20] [Server thread/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:40:20] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:40:20] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:242)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.World.g(World.java:1582)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:40:20] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:40:20] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:745)
```

For you'r replie:

>  It looks like the money was picked up by a hopper??? Do you know how that happened? Is it something you did or another player? 

I have no idea how this could happen to ..

**Comment by Rocologo** [comment]
Thanks for reporting this. It is only a warning and information to me. I will remove the warning for the Hopper in next release.

**Comment by Rocologo** [comment]
I have removed the warning for the Hopper, but you will get the message again it the item is picked up in another inventory. If this happens please report this again.

Its not clear to me if this is two errors (if they are related) or if this is only one error? If you see the seconds message again, please report this again and please show the full warning text from the console. If looks like something is missing?

**Comment by HalCroves** [comment]
Thanks for your reply. 
I was look the console log if y see this error.

Cordially
