### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v7.0.4

### ISSUE THREAD

**Issue by myfbone** [Rocologo/MobHunting#622]
[02:21:35 ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.0.4
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.15.2.jar:git-Paper-161]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.15.2.jar:git-Paper-161]
        at one.lindegaard.MobHunting.grinding.GrindingManager.isNetherGoldXPFarm(GrindingManager.java:146) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:672) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
~[patched_1.15.2.jar:git-Paper-161]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-161]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-16
1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper
-161]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[p
atched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Pap
er-161]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Pap
er-161]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Pape
r-161]
        at net.minecraft.server.v1_15_R1.EntityPigZombie.damageEntity(EntityPigZombie.java:138) ~[patched_1.15.2.jar:gi
t-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.b(EntityLiving.java:1530) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.Block.fallOn(Block.java:603) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.Entity.a(Entity.java:1078) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.a(EntityLiving.java:229) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:596) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2257) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2624) ~[patched_1.15.2.jar:git-Pap
er-161]
        at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525) ~[patched_1.15.2.jar:
git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.15.2.jar:git-Pap
er-161]
        at net.minecraft.server.v1_15_R1.EntityZombie.movementTick(EntityZombie.java:209) ~[patched_1.15.2.jar:git-Pape
r-161]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Pape
r-161]
        at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:769) ~[patched_1.15.2.jar:git-P
aper-161]
        at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:504) ~[patched_1.15.2.jar:git-Paper-161]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-16
1]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-161
]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-16
1]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-1
61]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by myfbone** [comment]
It's probably because I have zombie pigman spawners in regular world.

**Comment by Rocologo** [comment]
No I needed to check if the killings was in the same world.

This should be fixed now. Try this build:
https://fractal.lindegaard.one:8181/job/MobHunting/983/
