### ISSUE TITLE
Could not pass event PlayerDeathEvent to MobHunting v7.0.5-SNAPSHOT-B984 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by myfbone** [Rocologo/MobHunting#627]
[08:54:46 ERROR]: Could not pass event PlayerDeathEvent to MobHunting v7.0.5-SNAPSHOT-B984
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.rewards.CustomItems.getPlayerHead(CustomItems.java:92) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1944) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
~[patched_1.15.2.jar:git-Paper-183]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-18
3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper
-183]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:784) ~[p
atched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityPlayer.die(EntityPlayer.java:598) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Pap
er-183]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-
183]
        at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:754) ~[patched_1.15.2.jar:git-Pape
r-183]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1706) ~[patched_1.15.2.jar:git-Paper-183
]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2054) ~[patched_1.15.2.jar:git-Paper-
183]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:gi
t-Paper-183]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git
-Paper-183]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
 ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar
:git-Paper-183]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git
-Paper-183]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar
:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-1
83]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1052) ~[patched_1.15.2.jar:gi
t-Paper-183]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:
git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1022) ~[patched_1.15.2.jar:g
it-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:945) ~[patched_1.15.2.jar:git-Paper-1
83]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Rocologo** [comment]
Please try newest build: https://fractal.lindegaard.one:8181/job/MobHunting/
