### ISSUE TITLE
Could not pass event PlayerDeathEvent to MobHunting v7.0.5

### ISSUE THREAD

**Issue by sherwood2142** [Rocologo/MobHunting#628]
`[12:44:35 ERROR]: Could not pass event PlayerDeathEvent to MobHunting v7.0.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:286) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [kingdoms.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at one.lindegaard.MobHunting.MobHuntingManager.onPlayerDeath(MobHuntingManager.java:315) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor1168.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[kingdoms.jar:git-Spigot-79a30d7-acbc348]
        ... 20 more`

**Comment by Rocologo** [comment]
Do you know what happened here. It looks like if the player died from an arrow or something like that, but there was no shooter? Can you tell me when this happened?

**Comment by Rocologo** [comment]
I you enable debug "/mh debug" and see the same error the please give me the lines from the console before the error, this will give me a clue on whar happended

**Comment by rockbyo5** [comment]
still having a similar issue in 7.0.8, posted log on the last issue #640

**Comment by Rocologo** [comment]
fixed in Build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/
