### ISSUE TITLE
Could not pass event MobHuntEnableCheckEvent to MobHunting v7.0.5

### ISSUE THREAD

**Issue by Arcticcat340** [Rocologo/MobHunting#629]
I am having this error in console every time someone kills a mob. Any advice?

[21:07:35] [Server thread/ERROR]: Could not pass event MobHuntEnableCheckEvent to MobHunting v7.0.5
java.lang.IllegalAccessError: tried to access field au.com.mineauz.minigames.Minigames.plugin from class one.lindegaard.MobHunting.compatibility.MinigamesCompat
	at one.lindegaard.MobHunting.compatibility.MinigamesCompat.onPlayerJoinMinigame(MinigamesCompat.java:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-143]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
	at one.lindegaard.MobHunting.MobHuntingManager.isHuntEnabled(MobHuntingManager.java:147) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1184) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-143]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:768) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:504) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Rocologo** [comment]
Disable integration to minigames in config.yml

**Comment by Arcticcat340** [comment]
I still seem to be getting an error with minigames disabled.

[18:09:55] [Server thread/ERROR]: Could not pass event MobHuntEnableCheckEvent to MobHunting v7.0.5
java.lang.IllegalAccessError: tried to access field au.com.mineauz.minigames.Minigames.plugin from class one.lindegaard.MobHunting.compatibility.MinigamesCompat
	at one.lindegaard.MobHunting.compatibility.MinigamesCompat.onPlayerJoinMinigame(MinigamesCompat.java:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-143]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
	at one.lindegaard.MobHunting.MobHuntingManager.isHuntEnabled(MobHuntingManager.java:147) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onSkeletonShoot(MobHuntingManager.java:394) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-143]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1248) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:557) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1225) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1127) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntitySkeletonAbstract.a(EntitySkeletonAbstract.java:167) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PathfinderGoalBowShoot.e(SourceFile:128) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.15.2.jar:git-Paper-143]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
	at net.minecraft.server.v1_15_R1.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:119) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:686) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2596) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntitySkeletonAbstract.movementTick(EntitySkeletonAbstract.java:85) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:768) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:504) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Rocologo** [comment]
Could please tell me which version of Minigames you are using and where I can find the version?

PS. disableing the integration should work by the way!

**Comment by Rocologo** [comment]
Fixed in build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/
