### ISSUE TITLE
CMI integration requires a tweak?

### ISSUE THREAD

**Issue by mrfloris** [Rocologo/MobHunting#630]
```
[06:36:52] [Server thread/WARN]: [MobHunting] Task #203437 for MobHunting v7.0.5 generated an exception
java.lang.NoSuchMethodError: com.Zrips.CMI.CMI.getActionBar()Lcom/Zrips/CMI/utils/ActionBar;
        at one.lindegaard.MobHunting.compatibility.CMICompat.sendActionBarMessage(CMICompat.java:60) ~[?:?]
        at one.lindegaard.MobHunting.Messages.playerActionBarMessageNow(Messages.java:565) ~[?:?]
        at one.lindegaard.MobHunting.Messages.access$000(Messages.java:44) ~[?:?]
        at one.lindegaard.MobHunting.Messages$1.run(Messages.java:538) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Zrips** [comment]
Just to add on this one, new updated version of CMI, which will come out today, will have some rework on actionbar and titlemessage methods, which will be separate and moved to their own classes. So new methods to get them will be CMI#getActionBarManager() and CMI#getTitleMessageManager()

**Comment by Rocologo** [comment]
I was not aware the Zrips had changed the API. I will download newest version and try to use

 CMI#getActionBarManager() and CMI#getTitleMessageManager()

**Comment by Rocologo** [comment]
Fixed in V7.0.6

**Comment by mrfloris** [comment]
Thank you.But I think there's some debug stuff left over in this build.


<img width="667" alt="Screenshot 2020-04-25 at 17 17 00" src="https://user-images.githubusercontent.com/28841349/80283547-9eb75000-8718-11ea-9189-7ea8493e1611.png">

**Comment by Rocologo** [comment]
Sorry for the poor testing. I will fix it NOW! and make a neww release

**Comment by Rocologo** [comment]
V7.0.7 released
