### ISSUE TITLE
NPE fired on EntityDeathEvent 

### ISSUE THREAD

**Issue by teozfrank** [Rocologo/MobHunting#631]
Could not pass event EntityDeathEvent to MobHunting v7.0.7
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1545) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-e7dc2f5-a8ec1d6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/PrimarySkillType
at one.lindegaard.MobHunting.compatibility.McMMOCompatHelper.getSKillTypeName(McMMOCompatHelper.java:20) ~[?:?]
at one.lindegaard.MobHunting.compatibility.McMMOCompat.getSkilltypeName(McMMOCompat.java:104) ~[?:?]
at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1807) ~[?:?]
at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-e7dc2f5-a8ec1d6]
... 24 more

**Comment by teozfrank** [comment]
Running  mcMMO version 2.0.0-SNAPSHOT

**Comment by teozfrank** [comment]
Ah this could be an incompatability with latest mcmmo API snapshots.

**Comment by Rocologo** [comment]
Correct. I will have to check if the API has changed.

**Comment by Rocologo** [comment]
I'm not sure which version you actually use? Your version number does not match any of these versions. 

https://www.spigotmc.org/resources/official-mcmmo-classic.2445/
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348
