### ISSUE TITLE
Lorinths RPG (Integration broken)

### ISSUE THREAD

**Issue by HavaTequila** [Rocologo/MobHunting#632]
Hello,

today I tested out LRPG (1.6.8 and 1.7) in combination with Mob Hunting (7.0.5 and 7.0.7). 
After a server restart I get the following error every 0.5 seconds. 
Already got in touch with the other dev and he suggested that the LRPG integration may be broken inside Mob Hunting. If you need further details please contact me.

`[18:53:08 ERROR]: Could not pass event CreatureSpawnEvent to MobHunting v7.0.7
java.lang.NoClassDefFoundError: me/Lorinth/LRM/LorinthsRpgMobs
        at one.lindegaard.MobHunting.compatibility.LorinthsRpgMobsCompat.isLorinthsRpgMobs(LorinthsRpgMobsCompat.java:65) ~[?:?]
        at one.lindegaard.MobHunting.compatibility.LorinthsRpgMobsCompat.LorinthsRpgMobsSpawnEvent(LorinthsRpgMobsCompat.java:99) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-226]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:631) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:552) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1260) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1167) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.SpawnerCreature.spawnMobs(SpawnerCreature.java:123) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$tickChunks$12(ChunkProviderServer.java:847) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:287) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:779) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:715) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by Rocologo** [comment]
fixed in 7.0.8
