### ISSUE TITLE
unknown server error appears when enderman is killed!

### ISSUE THREAD

**Issue by benpryde** [Rocologo/MobHunting#639]
I looked through blacklist areas, grinding configurations. nothing helps! what is this error?

[19:25:13] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.0.8
java.lang.NullPointerException: null
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1384) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-264]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityEnderman.damageEntity(EntityEnderman.java:294) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1141) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1706) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2088) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1220) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-264]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Rocologo** [comment]
fixed in build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/
