### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#641]
Spigot 1.15.2
MH 7.0.9-SNAPSHOT-B1012

Getting a lot of these, and no BagOfGold drops.
Major issue. Disabled BagOfGold drops in config.yml, until this issue is resolved.
```
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog killed a Creeper (Minecraft)@(world_skyblock:258,124,257)
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] KillAllowed: Mob killed by _SlimeDog was allowed by WorldGuard
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] Basic Prize= 50 for killing a Creeper
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog used a weapon: BOW
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] Checking kills in this area. DampenedKills=6. Penalty begins at 10. Max is 20
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] DampenedKills are below half of limit: 20
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog has killed 2 Creeper in 3 seconds. Avg.kill time 1 must greater than 12.0 when 10 mobs is killed.
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog is not Speed Grinding
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog has no Rank Multiplier
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] Killstreak=1, level=0, multiplier=1.0 
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] Reward rounded to 50.0
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] [AchievementBlocked] Achievements is disabled in world:world_skyblock
[19:02:39] [Server thread/INFO]: [MobHunting] [Debug] RecordKill: _SlimeDog killed a Creeper (Minecraft) Cash= 50
[19:02:39] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.0.9-SNAPSHOT-B1012
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:729) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:367) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:280) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:191) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:626) ~[spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.World.a(World.java:694) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
```

**Comment by SlimeDog** [comment]
```
>mh debug
[12:15:41] [Server thread/INFO]: [MobHunting] Debugmode enabled. Check server console.
[12:15:44] [Server thread/INFO]: [MobHunting] [Debug] Refreshed 0 leaderboards.
[12:15:44] [Server thread/INFO]: [MobHunting] [Debug] Refreshed 1 ranks.
[12:16:44] [Server thread/INFO]: [MobHunting] [Debug] Refreshed 0 leaderboards.
[12:16:44] [Server thread/INFO]: [MobHunting] [Debug] Refreshed 1 ranks.
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog killed a Zombie (Minecraft)@(world_skyblock:256,125,242)
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] KillAllowed: Mob killed by _SlimeDog was allowed by WorldGuard
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] Basic Prize= 50 for killing a Zombie
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog used a weapon: STONE_AXE
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] Kill not within 15.0 blocks from previous kill. Dampened Kills reset to 0
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog has killed 1 Zombie in 0 seconds. Avg.kill time 0 must greater than 12.0 when 10 mobs is killed.
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog is not Speed Grinding
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog has no Rank Multiplier
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] Killstreak=7, level=1, multiplier=1.0 
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] Reward rounded to 50.0
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] [AchievementBlocked] Achievements is disabled in world:world_skyblock
[12:16:59] [Server thread/INFO]: [MobHunting] [Debug] RecordKill: _SlimeDog killed a Zombie (Minecraft) Cash= 50
[12:16:59] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.0.9-SNAPSHOT-B1012
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:729) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:300) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1547) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[?:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
>mh debug
[12:17:27] [Server thread/INFO]: [MobHunting] Debugmode disabled.
```

**Comment by SlimeDog** [comment]
Here's another, with trace after the NPE:
```
[00:08:57] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.0.9-SNAPSHOT-B1012
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:729) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:300) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityPigZombie.damageEntity(EntityPigZombie.java:138) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityWolf.B(EntityWolf.java:253) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.a(SourceFile:139) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.e(SourceFile:131) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.e(SourceFile:55) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_15_R1.PathfinderGoalSelector.doTick(SourceFile:80) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2524) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:512) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityAgeable.movementTick(EntityAgeable.java:170) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityAnimal.movementTick(EntityAnimal.java:28) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityWolf.movementTick(EntityWolf.java:151) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2356) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.EntityWolf.tick(EntityWolf.java:167) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:626) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.World.a(World.java:694) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(String.java:2143) ~[?:?]
        at one.lindegaard.Core.rewards.CoreCustomItems.getCustomtexture(CoreCustomItems.java:142) ~[?:?]
        at one.lindegaard.MobHunting.rewards.RewardManager.dropMoneyOnGround_RewardManager(RewardManager.java:380) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1707) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-05-28-0347:git-Spigot-2f5d615-aae46f8]
        ... 42 more
```
This might be caused by
```
    money:
      amount: '0'
      chance: 1.0
```

**Comment by SlimeDog** [comment]
https://mineskin.org/42793

**Comment by Rocologo** [comment]
I think this i fixed in newest SNAPSHOTS

https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/

Please take backup before updating to BagOfGold 3.0.0 or MobHunting 7.5.0 I have mad big and many changes in these builds.

I need help with the testing. 

When you use ANY one of these two build you will get some new files in the folder BagOfGold called bagofgoldcore.yml and bagofgoldcore.db. The both contain shared settings / data used by both plugins. 

It also contain the new mobs in MC 1.16.1 (Hoglin, Piglin, Strider and Zoglin)

Please create a new ticked if you find new bugs.

**Comment by SlimeDog** [comment]
This issue has not recurred with B1032.
