### ISSUE TITLE
SQLITE_BUSY

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#650]
Spigot 1.15.2
MobHunting 7.5.0-b1024

We are still seeing these. In this case, when a player disconnected.
```
[18:23:19] [MH TaskThread/WARN]: one.lindegaard.Core.storage.DataStoreException: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[18:23:19] [MH TaskThread/WARN]:        at one.lindegaard.Core.storage.DatabaseDataStore.savePlayerSettings(DatabaseDataStore.java:277)
[18:23:19] [MH TaskThread/WARN]:        at one.lindegaard.Core.storage.async.StoreTask.run(StoreTask.java:29)
[18:23:19] [MH TaskThread/WARN]:        at one.lindegaard.Core.storage.async.StoreTask.run(StoreTask.java:10)
[18:23:19] [MH TaskThread/WARN]:        at one.lindegaard.Core.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:313)
[18:23:19] [MH TaskThread/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[18:23:19] [MH TaskThread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:941)
[18:23:19] [MH TaskThread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:953)
[18:23:19] [MH TaskThread/WARN]:        at org.sqlite.core.DB.throwex(DB.java:918)
[18:23:19] [MH TaskThread/WARN]:        at org.sqlite.core.DB.executeBatch(DB.java:805)
[18:23:19] [MH TaskThread/WARN]:        at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:86)
[18:23:19] [MH TaskThread/WARN]:        at one.lindegaard.Core.storage.DatabaseDataStore.savePlayerSettings(DatabaseDataStore.java:260)
[18:23:19] [MH TaskThread/WARN]:        ... 3 more
```

**Comment by Rocologo** [comment]
I think this i fixed in newest SNAPSHOTS

https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/

Please take backup before updating to BagOfGold 3.0.0 or MobHunting 7.5.0 I have mad big and many changes in these builds.

I need help with the testing. 

When you use ANY one of these two build you will get some new files in the folder BagOfGold called bagofgoldcore.yml and bagofgoldcore.db. The both contain shared settings / data used by both plugins. 

It also contain the new mobs in MC 1.16.1 (Hoglin, Piglin, Strider and Zoglin)

Please create a new ticked if you find new bugs.

**Comment by SlimeDog** [comment]
This issue has not been encountered in 30 minutes of testing.
