### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#657]
Spigot 1.16.1
MH 7.5.0-SNAPSHOT-B1051
updated from MH 7.5.0-SNAPSHOT-B1049

On server start-up (ie., enable):
```
[21:40:52] [Server thread/WARN]: java.io.FileNotFoundException: plugins/BagOfGold/rewards.yml (No such file or directory)
[21:40:52] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[21:40:52] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[21:40:52] [Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[21:40:52] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[21:40:52] [Server thread/WARN]: 	at one.lindegaard.Core.rewards.RewardBlockManager.loadAllStoredRewards(RewardBlockManager.java:103)
[21:40:52] [Server thread/WARN]: 	at one.lindegaard.Core.rewards.RewardBlockManager.<init>(RewardBlockManager.java:38)
[21:40:52] [Server thread/WARN]: 	at one.lindegaard.Core.Core.<init>(Core.java:58)
[21:40:52] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:143)
[21:40:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:40:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[21:40:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:40:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491)
[21:40:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405)
[21:40:52] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
[21:40:52] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[21:40:52] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
[21:40:52] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[21:40:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
and the file does not exist.

**Comment by Rocologo** [comment]
V 7.5.0 Released. I close this ticket now.
