### ISSUE TITLE
Error on hook with HerobrineAI

### ISSUE THREAD

**Issue by FabioZumbi12** [Rocologo/MobHunting#660]
Using MH with HerobrineAI i having this errors on console:

```
[13:27:09] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobHunting v7.5.0
java.lang.NoSuchMethodError: net.theprogrammersworld.herobrine.Herobrine.getEntityManager()Lnet/theprogrammersworld/herobrine/nms/entity/EntityManager;
	at one.lindegaard.MobHunting.compatibility.HerobrineCompat.isHerobrineMob(HerobrineCompat.java:71) ~[?:?]
	at one.lindegaard.MobHunting.compatibility.HerobrineCompat.onHerobrineMobSpawnEvent(HerobrineCompat.java:114) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.1.jar:git-Paper-39]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-39]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-39]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-39]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:653) ~[patched_1.16.1.jar:git-Paper-39]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:574) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.WorldServer.addEntity0(WorldServer.java:1152) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.WorldServer.addEntity(WorldServer.java:1060) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.TileEntityBeehive.releaseBee(TileEntityBeehive.java:185) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.TileEntityBeehive.releaseBee(TileEntityBeehive.java:156) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.TileEntityBeehive.y(TileEntityBeehive.java:261) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.TileEntityBeehive.tick(TileEntityBeehive.java:277) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.World.tickBlockEntities(World.java:851) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:563) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-39]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-39]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

**Comment by Rocologo** [comment]
It seems the Dev of HerobrineAI has changed and removed a java class which make MobHunting fail from V1.15.2 I need to talk to the dev and ask him how I can detect Herobrine.

**Comment by Rocologo** [comment]
Build 1057 has now support for HerobrineAI 2.0.3+

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
Also I have changed the way the Rewards are read from server-start. You will still see errors in the console, but it will skip the "broken" rewards and remove them from rewards.yml

**Comment by FabioZumbi12** [comment]
Cool, ill try on next server reboot, thank you!!
