### ISSUE TITLE
Could not pass event MythicMobSpawnEvent to MobHunting v2.8.5 (or any of last versions).

### ISSUE THREAD

**Issue by ntgh-dimako** [Rocologo/MobHunting#7]
New error after new version of mm came out:
[00:42:09] [Server thread/ERROR]: Could not pass event MythicMobSpawnEvent to MobHunting v2.8.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at net.elseland.xikage.MythicMobs.Mobs.MythicMob.spawn(MythicMob.java:620) ~[?:?]
	at net.elseland.xikage.MythicMobs.Mobs.MobSpawner.SpawnMythicMob(MobSpawner.java:35) ~[?:?]
	at net.elseland.xikage.MythicMobs.RandomSpawning.RandomSpawner.spawn(RandomSpawner.java:207) ~[?:?]
	at net.elseland.xikage.MythicMobs.RandomSpawning.RandomSpawnerManager.doSpawns(RandomSpawnerManager.java:76) ~[?:?]
	at net.elseland.xikage.MythicMobs.RandomSpawning.RandomSpawnerManager.lambda$spawnMobs$2(RandomSpawnerManager.java:63) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) [?:1.8.0_74]
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) [?:1.8.0_74]
	at net.elseland.xikage.MythicMobs.RandomSpawning.RandomSpawnerManager.spawnMobs(RandomSpawnerManager.java:62) [MythicMobs-2.4.0.jar:?]
	at net.elseland.xikage.MythicMobs.Clock.MythicMobsClock.run(MythicMobsClock.java:48) [MythicMobs-2.4.0.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [custom_server.jar:git-Spigot-944aa20-8d16fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoSuchFieldError: MobName
	at one.lindegaard.MobHunting.compatability.MythicMobsCompat.onMythicMobSpawnEvent(MythicMobsCompat.java:194) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom_server.jar:git-Spigot-944aa20-8d16fc0]
	... 19 more

**Comment by Rocologo** [comment]
Thank. I guess the developer of MythicMobs has changed something. I will investigate.

**Comment by ntgh-dimako** [comment]
NP. Good luck with that.

**Comment by Rocologo** [comment]
You should disable integration to mobhunting until i have fixed the bug.

**Comment by Rocologo** [comment]
I have found the bug and will release a new version 2.8.6 where this is fixed. The API of MythicMobs was changed - this broke my plugin.

**Comment by Rocologo** [comment]
Please let me know if this is fixed.

**Comment by ntgh-dimako** [comment]
Didn't notice any errors in new version.
