### ISSUE TITLE
paper 1.16.5 broke mobhunting

### ISSUE THREAD

**Issue by Cloman** [Rocologo/MobHunting#711]
updated spigot to 1.16.5 build 436.

[09:14:14] [Server thread/ERROR]: Error occurred while enabling MobHunting v7.5.7 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant one.lindegaard.Core.rewards.RewardType.MemorySection[path='212.type', root='YamlConfiguration']
	at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
	at one.lindegaard.Core.rewards.RewardType.valueOf(RewardType.java:5) ~[?:?]
	at one.lindegaard.Core.rewards.Reward.read(Reward.java:259) ~[?:?]
	at one.lindegaard.Core.rewards.RewardBlockManager.load(RewardBlockManager.java:131) ~[?:?]
	at one.lindegaard.Core.rewards.RewardBlockManager.<init>(RewardBlockManager.java:39) ~[?:?]
	at one.lindegaard.Core.Core.<init>(Core.java:57) ~[?:?]
	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:143) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-436]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-436]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-436]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-436]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-436]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-436]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-436]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-436]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-436]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:14:14] [Server thread/INFO]: [MobHunting] Disabling MobHunting v7.5.7

**Comment by Momshroom** [comment]
Mobhunting is working fine for me in paper 1.16.5 using 7.5.8-SNAPSHOT-B1100, except the database connection closes very slowly. (both paper 446 and 437)

**Comment by Cloman** [comment]
looks like somehow rewards.yml has been corrupted :/
found these things in the yml: &id001 and &id002.
One i found behind the id and on i found in location.
After this i found most of them behind type: value

here the example:

'96': &id001
  location:
    ==: org.bukkit.Location
    world: world
    x: -1300.0
    y: 66.0
    z: 297.0
    pitch: 0.0
    yaw: 0.0
  displayname: §9Shulker


'212':
  location: &id002
    ==: org.bukkit.Location
    world: world
    x: 2.49211E7
    y: 97.0
    z: -2.4187739E7
    pitch: 0.0
    yaw: 0.0
  displayname: §9Silverfish
  money: '0.00000'
  type: *id001

similar i found in type: 

'218':
  location:
    ==: org.bukkit.Location
    world: world
    x: -1119.0
    y: 63.0
    z: 424.0
    pitch: 0.0
    yaw: 0.0
  displayname: §9Llama
  money: '0.00000'
  type: *id002
