### ISSUE TITLE
Console error when mobs killed with 110percent multiplier. (I haven't tried others)

### ISSUE THREAD

**Issue by Momshroom** [Rocologo/MobHunting#717]
When I give players the permission mobhunting.multiplier.110percent mobs stop paying when killed and this console error occurs every time a mob is killed:
`[01:58:26 ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.5.8-SNAPSHOT-B1100                                                                                      
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap
')                                                                                                                                                                               
        at one.lindegaard.MobHunting.modifier.RankBonus.getMultiplier(RankBonus.java:32) ~[?:?]                                                                                  
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1533) ~[?:?]                                                                            
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-508]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-508]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-508]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-508]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:826) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1504) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1426) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1268) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityArrow.a(EntityArrow.java:333) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:125) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityArrow.tick(EntityArrow.java:176) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:846) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:531) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1362) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-508]
        at java.lang.Thread.run(Thread.java:834) [?:?]  `

**Comment by Rocologo** [comment]
Please be more specific on this one. 

Which multiplier is it exactly you are talking about. 

Notice that the error is saying you are using a string where it should be a number? So show me what you wrote exactly?
