### ISSUE TITLE
MobHunting v7.5.7 generated an exception - com.Zrips.CMI.Modules.ActionBar.ActionBarManager 

### ISSUE THREAD

**Issue by gerardvanschip** [Rocologo/MobHunting#719]
Every time someone kills a mob we get this error in the log file. I thought I could simply disable the hook in CMI but disabling that does not stop this from happening.

`[14:58:47] [Server thread/WARN]: [MobHunting] Task #174275 for MobHunting v7.5.7 generated an exception
java.lang.NoSuchMethodError: 'com.Zrips.CMI.Modules.ActionBar.ActionBarManager com.Zrips.CMI.CMI.getActionBarManager()'
	at one.lindegaard.MobHunting.compatibility.CMICompat.sendActionBarMessage(CMICompat.java:62) ~[?:?]
	at one.lindegaard.MobHunting.Messages.playerActionBarMessageNow(Messages.java:563) ~[?:?]
	at one.lindegaard.MobHunting.Messages.access$000(Messages.java:46) ~[?:?]
	at one.lindegaard.MobHunting.Messages$1.run(Messages.java:536) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3158-Spigot-f773da8-470050a]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by Rocologo** [comment]
Which version of CMI do you use?

**Comment by Rocologo** [comment]
I have contacted Zrips who is the Dev of CMI. I think he has changed something and this is why MobHunting fails.

**Comment by Rocologo** [comment]
I have contacted Zrips who is the Dev of CMI. I think he has changed something and this is why MobHunting fails.

**Comment by Rocologo** [comment]
I have tested MobHunting against CMI 9.1.4.0 and it seems to be fixed now.
