### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Rocologo/MobHunting#744]
[11:50:42 WARN]: [MobHunting] Task #1151 for MobHunting v8.1.2 generated an exception
java.lang.NullPointerException: Cannot invoke "io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(org.bukkit.entity.Player)" because the return value of "one.lindegaard.MobHunting.MobHunting.getAdvancementManager()" is null
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:664) ~[MobHunting-8.1.2.jar:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:602) ~[MobHunting-8.1.2.jar:?]
        at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:270) ~[MobHunting-8.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1666]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1666]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

And after a while it stops working at all, i was not grinding, i was exploring the world.

**Comment by TDMidkwhatisxd** [comment]
i guess this plugin is abandoned -_-
