### ISSUE TITLE
Error Spamming in Latest Purpur-1.19 and MythicMob compatibility isn't working

### ISSUE THREAD

**Issue by SamGamerYT** [Rocologo/MobHunting#748]
[02:06:20 INFO]: [MobHunting] Enabling compatibility with MythicMobs (5.1.1-SNAPSHOT-a92c1abb)
[02:06:20 ERROR]: [MobHunting] Plugin MobHunting v8.1.5 has failed to register events for class one.lindegaard.MobHunting.compatibility.MythicMobsV400Compat because io/lumine/xikage/mythicmobs/mobs/MythicMob does not exist.

[02:07:12 WARN]: [MobHunting] Task #3401 for MobHunting v8.1.5 generated an exception
java.lang.NullPointerException: Cannot invoke "io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(org.bukkit.entity.Player)" because the return value of "one.lindegaard.MobHunting.MobHunting.getAdvancementManager()" is null
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:664) ~[MobHunting-8.1.5.jar:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:602) ~[MobHunting-8.1.5.jar:?]
        at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:270) ~[MobHunting-8.1.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1735]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1518) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1209) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1735]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Rocologo** [comment]
This is fixed in V8.1.6 which was released today
