### ISSUE TITLE
Console error spam.

### ISSUE THREAD

**Issue by SuperPyroManiac** [Rocologo/MobHunting#749]
Plugin keeps generating errors from "Could not pass event EntityDeathEvent to MobHunting v8.1.7"

Full error: https://pastebin.com/z7cnYhXY
![image](https://user-images.githubusercontent.com/1407314/187580988-a79cb118-5ad4-4183-bfbb-bae2108fd426.png)

**Comment by Rocologo** [comment]
I need to see the whole error text not only the beginning, but it could be because you have added a world which does not exist or something?



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SuperPyroManiac ***@***.***>
Dato: 31.08.2022 04.44 (GMT+01:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Subscribed ***@***.***>
Emne: [Rocologo/MobHunting] Console error spam. (Issue #749)


Plugin keeps generating errors from "Could not pass event EntityDeathEvent to MobHunting v8.1.7"

Full error: https://pastebin.com/z7cnYhXY
[image]<https://user-images.githubusercontent.com/1407314/187580988-a79cb118-5ad4-4183-bfbb-bae2108fd426.png>

**Comment by SuperPyroManiac** [comment]
Pastebin in the report shows entire log. Here it is here though.

`java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.Location.getWorld()" is null
at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:470) ~[MobHunting-8.1.7.jar:?]
at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:67) ~[MobHunting-8.1.7.jar:?]
at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:667) ~[MobHunting-8.1.7.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-134]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:223) ~[?:?]
at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:906) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.world.entity.Entity.baseTick(Entity.java:837) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:393) ~[?:?]
at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2909) ~[?:?]
at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:116) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1159) ~[?:?]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:696) ~[?:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1554) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-134]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-134]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by SuperPyroManiac** [comment]
Worlds are all loaded and working, so not sure how that would cause it.

**Comment by Rocologo** [comment]
Have you deleted any world's lately?



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SuperPyroManiac ***@***.***>
Dato: 31.08.2022 07.04 (GMT+01:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/MobHunting] Console error spam. (Issue #749)


Worlds are all loaded and working, so not sure how that would cause it.

**Comment by Rocologo** [comment]
Try enable debug using /mh debug and give me some more lines from the server log before the error.



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SuperPyroManiac ***@***.***>
Dato: 31.08.2022 07.03 (GMT+01:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/MobHunting] Console error spam. (Issue #749)


Pastebin in the report shows entire log. Here it is here though.

java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.Location.getWorld()" is null at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:470) ~[MobHunting-8.1.7.jar:?] at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:67) ~[MobHunting-8.1.7.jar:?] at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:667) ~[MobHunting-8.1.7.jar:?] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-134] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?] at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?] at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?] at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:223) ~[?:?] at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:906) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.world.entity.Entity.baseTick(Entity.java:837) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:393) ~[?:?] at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?] at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2909) ~[?:?] at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?] at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:116) ~[?:?] at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1159) ~[?:?] at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?] at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:696) ~[?:?] at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1554) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-134] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-134] at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SuperPyroManiac** [comment]
No worlds have been deleted. Here is the log with debug on.

I think I figured it out though. Looks like sometimes when NPC sentinels kill a mob while I am in another world, the error may popup. Log in next comment:

**Comment by SuperPyroManiac** [comment]
`[05:25:20] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:25:20] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Skeleton (Minecraft)@(world:74,72,-126)
[05:25:20] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:25:20] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:25:24] [Server thread/INFO]: SuperPyroManiac issued server command: /gmc
[05:25:38] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:25:38] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:26,72,-128)
[05:25:38] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:1).
[05:25:38] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:25:38] [Server thread/INFO]: [MobHunting] [Debug] MOB_ID=0
[05:25:46] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:25:46] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:25,76,-133)
[05:25:46] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:1).
[05:25:46] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:25:47] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:25:47] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:34,73,-126)
[05:25:47] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:25:47] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:25:49] [Server thread/INFO]: [MobHunting] [Debug] MOB_ID=0
[05:25:52] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v8.1.7
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.Location.getWorld()" is null
	at one.lindegaard.MobHunting.grinding.GrindingManager.isGrindingArea(GrindingManager.java:470) ~[MobHunting-8.1.7.jar:?]
	at one.lindegaard.MobHunting.grinding.GrindingManager.registerDeath(GrindingManager.java:67) ~[MobHunting-8.1.7.jar:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:667) ~[MobHunting-8.1.7.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-134]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
	at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:223) ~[?:?]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:824) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:393) ~[?:?]
	at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2909) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
	at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:116) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1159) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:696) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1554) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:25:56] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:25:56] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:33,72,-125)
[05:25:56] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:25:56] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:00] [Server thread/INFO]: TPS from last 1m, 5m, 15m: 20.0, 20.0, 20.0
[05:26:00] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:26:00] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:26,72,-126)
[05:26:00] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:26:00] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:01] [Server thread/INFO]: [MobHunting] [Debug] MOB_ID=0
[05:26:09] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:26:09] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:26,72,-126)
[05:26:09] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:26:09] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:27,72,-126)
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:27,72,-126)
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:26:10] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:13] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:26:13] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:28,73,-125)
[05:26:13] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:26:13] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:15] [Server thread/INFO]: [MobHunting] [Debug] MOB_ID=0
[05:26:22] [Server thread/INFO]: [MobHunting] [Debug] ======================== New kill ==========================
[05:26:22] [Server thread/INFO]: [MobHunting] [Debug] Guard killed a Zombie (Minecraft)@(world:29,73,-126)
[05:26:22] [Server thread/INFO]: [MobHunting] [Debug] KillBlocked: Killer is a Citizen NPC (ID:3).
[05:26:22] [Server thread/INFO]: [MobHunting] [Debug] ======================= kill ended (2)======================
[05:26:38] [MH StoreThread/INFO]: [MobHunting] [Debug] Saving whitelisted and blacklisted areas to disk.
[05:26:48] [Server thread/INFO]: [MobHunting] [Debug] Refreshed 1 ranks.
[05:26:48] [Server thread/INFO]: [MobHunting] [Debug] No MasterMobHunters ???`

**Comment by SuperPyroManiac** [comment]
https://pastebin.com/RuZipWwy

**Comment by SuperPyroManiac** [comment]
I take that back, even with the NPC's removed the error still happens. Debug shows nothing extra from the original log.

Im going to let the server run overnight with the debug on and will report back tomorrow if there is anything else showing up.

**Comment by Rocologo** [comment]
At Work now 😊

I still think it has something todo with the NPC and/or the Grinding detection, unfortunately I forgot my laptop at home, so I will not be able to investigate this until tonight.

I notice that the ”world” is null, which shoul not be possible???
Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.Location.getWorld()" is null

I hate bugs, which I cant reproduce at home, they are so hard to find ☹

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: ***@***.***>
Sendt: 31. august 2022 07:33
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [Rocologo/MobHunting] Console error spam. (Issue #749)


I take that back, even with the NPC's removed the error still happens. Debug shows nothing extra from the original log.

Im going to let the server run overnight with the debug on and will report back tomorrow if there is anything else showing up.

**Comment by SuperPyroManiac** [comment]
Yeah, i'll remove my citizens plugins and see if the error continues. Seems to happen only in "world" when I am in another world.

When I logged off last night and let it run there were no issues all night. I assume because no mobs spawn without players.

**Comment by Rocologo** [comment]
I have been looking at my code. It looks like the file blacklist.yml in the MobHunting folder is containing a "non existing" world. I cant tell how that could happen if you have not deleted any worlds.

I will add a test and examine if the worldId in the file actually exsists. If not the code will continue without adding the areas to blacklisted areas.

**Comment by Rocologo** [comment]
Please test this snapshot. I have added a test to see if the worlds in blacklist.yml and whitelist.yml exists when MobHunting is loaded.

https://jenkins.lindegaard.one/job/MobHunting/124/

If this does not fix the bud, then please post the new information from the console log.

**Comment by SuperPyroManiac** [comment]
Got the error with the custom version. Same issue.
https://pastebin.com/a8bqj0gK

**Comment by Rocologo** [comment]
Now I see what happening. It a bat killed by lava. That's probably not s farm. I will check my code again.



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SuperPyroManiac ***@***.***>
Dato: 01.09.2022 01.50 (GMT+01:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/MobHunting] Console error spam. (Issue #749)


Got the error with the custom version. Same issue.
https://pastebin.com/a8bqj0gK

**Comment by SuperPyroManiac** [comment]
Glad you were able to find it. Had some testers on today and it was really blowing up the log with errors when multiple people are on.

**Comment by Rocologo** [comment]
Please test this snapshot
https://jenkins.lindegaard.one/job/MobHunting/125/

**Comment by SuperPyroManiac** [comment]
Issue is resolved using that build.

**Comment by Rocologo** [comment]
Nice to hear. Thank you for your help with the testing.

**Comment by Rocologo** [comment]
Ahh. I will check my code for what's happens when a NPC kills a mob in another world.


Good observation!



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SuperPyroManiac ***@***.***>
Dato: 31.08.2022 07.28 (GMT+01:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/MobHunting] Console error spam. (Issue #749)


No worlds have been deleted. Here is the log with debug on.

I think I figured it out though. Looks like sometimes when NPC sentinels kill a mob while I am in another world, the error may popup. Log in next comment:

**Comment by Rocologo** [comment]
You are are right. It looks like it has something to do with your NPC / Guard. I will check that but I have to go to work now.



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SuperPyroManiac ***@***.***>
Dato: 31.08.2022 07.28 (GMT+01:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/MobHunting] Console error spam. (Issue #749)


https://pastebin.com/RuZipWwy
