### ISSUE TITLE
Could not pass event PlayerDeathEvent to MobHunting v8.1.8

### ISSUE THREAD

**Issue by Waterman1001** [Rocologo/MobHunting#754]
Maybe add a null check for if the shooter is null?

`[16:45:00 ERROR]: Could not pass event PlayerDeathEvent to MobHunting v8.1.8
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.bukkit.entity.Projectile.getShooter()" is null
at one.lindegaard.MobHunting.MobHuntingManager.onPlayerDeath(MobHuntingManager.java:320) ~[MobHunting-8.1.8.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-246]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:906) ~[paper-1.19.2.jar:git-Paper-246]
at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:881) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:982) ~[?:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1044) ~[?:?]
at net.minecraft.world.entity.projectile.FireworkRocketEntity.dealExplosionDamage(FireworkRocketEntity.java:274) ~[?:?]
at net.minecraft.world.entity.projectile.FireworkRocketEntity.explode(FireworkRocketEntity.java:192) ~[?:?]
at net.minecraft.world.entity.projectile.FireworkRocketEntity.onHitBlock(FireworkRocketEntity.java:216) ~[?:?]
at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:186) ~[?:?]
at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
at net.minecraft.world.entity.projectile.FireworkRocketEntity.tick(FireworkRocketEntity.java:165) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1192) ~[?:?]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:730) ~[?:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-246]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-246]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-246]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Thank you in advance for updating this! :)

**Comment by Rocologo** [comment]
I need you to test this again and please explain how I reproduce the bug. Please provide the new error text after upgrading to 8.5.0
