### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Rocologo/MobHunting#758]
[09:11:13 WARN]: [MobHunting] Task #3666 for MobHunting v8.5.1 generated an exception
java.lang.NullPointerException: Cannot invoke "io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(org.bukkit.entity.Player)" because the return value of "one.lindegaard.MobHunting.MobHunting.getAdvancementManager()" is null
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:665) ~[MobHunting-8.5.1.jar:?]
        at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:603) ~[MobHunting-8.5.1.jar:?]
        at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:270) ~[MobHunting-8.5.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]

**Comment by enigma072485** [comment]
I am also getting this error on version 8.5.4 running on purpur minecraft 1.20.4, I know 1.20.4 isn't officially supported but I wanted to report this anyways. Only happens when a player logs into the server.

```
WARN02:37:21
[MobHunting]: Task #915 for MobHunting v8.5.4 generated an exception
Console02:37:21
java.lang.NullPointerException: Cannot invoke "io.chazza.advancementapi.AdvancementManager.updatePlayerAdvancements(org.bukkit.entity.Player)" because the return value of "one.lindegaard.MobHunting.MobHunting.getAdvancementManager()" is null
at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:665) ~[MobHunting-8.5.4.jar:?]
at one.lindegaard.MobHunting.achievements.AchievementManager$3.onCompleted(AchievementManager.java:603) ~[MobHunting-8.5.4.jar:?]
at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:266) ~[MobHunting-8.5.4.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2159]
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2159]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2159]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2159]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2159]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2159]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2159]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
